import { D, C } from '../lib/draw.js';
import values from '../data/fundamentals/numbers.json' with { type: 'json' };
import { canvas, flow, cards, ledger, lanes, map, cover } from '../lib/fundamentals-figures.js';
const N = values.cn;
const stages = ['Network models and\nphysical signals','Data link and\nEthernet switching','VLANs and\nIP addressing','IP forwarding\nand routing','Transport and TCP','Flow and\ncongestion control','DNS and HTTP','QUIC, TLS and\nweb sessions','Proxies, tunnels\nand firewalls','Socket programming\nand I/O','CDN, P2P and\ncloud networking','The complete\nbrowser request'];
export function where_fund_cn(stage=99){ return map('where_fund_cn', stages, stage); }
export function cover_fund_cn(){ return cover('cover_fund_cn',['Computer','networks'],['Ethernet, IP, TCP, TLS and HTTP in one packet path.','Follow Finch from a private address to a public server.'],[['Put bytes on wire','signals, frames, errors'],['Choose the next hop','ARP, IP, routes, NAT'],['Protect the exchange','TCP, TLS, HTTP'],['Operate the path','proxies, sockets, cloud']],2); }
const f = (id, cap, labels, notes=[], focus=1) => flow(id, cap, labels, notes, focus);
const c = (id, cap, headers, rows, focus=0) => ledger(id, cap, headers, rows, focus);
export function cn_network(){return cards('cn_network','A NETWORK CONNECTS ENDPOINTS THROUGH SHARED RULES',[['LAN','one local site'],['WAN','several links and routers'],['Intranet','private administrative reach'],['Internet','interconnected independent networks']],0);}
export function cn_topology(){return cards('cn_topology','TOPOLOGIES HAVE DIFFERENT SHARED FAILURE POINTS',[['Star','central device joins access links'],['Bus','hosts share one medium'],['Ring','each host has two neighbours'],['Mesh','several alternate links']],0);}
export function cn_clients(){return cards('cn_clients','ENDPOINT ROLES CHANGE THE TRAFFIC PATTERN',[['Client-server','client requests a service'],['Peer-to-peer','each peer both asks and serves'],['Circuit','reserved path state'],['Packet','each packet is forwarded']],3);}
export function cn_metrics(){return c('cn_metrics','A PACKET PAYS TRANSMISSION, PROPAGATION, QUEUE AND PROCESSING',['quantity','value','meaning'],[['transmission','0.12 ms','1,500 bytes at 100 Mb/s'],['propagation','5 ms','1,000,000 m at 200,000,000 m/s'],['processing','0.05 ms','one forwarding step'],['queue','0.5 ms','waiting before service']],2);}
export function cn_layers(){return cards('cn_layers','EACH LAYER OWNS ONE KIND OF DECISION',[['Application','HTTP names the resource'],['Transport','TCP identifies the process'],['Network','IP selects the next hop'],['Link','Ethernet reaches the neighbour'],['Physical','signals carry bits']],0);}
export function cn_encapsulation(){return f('cn_encapsulation','EACH LOWER LAYER WRAPS THE UPPER BYTES',['HTTP payload','TCP segment','IP packet','Ethernet frame','signals'],['method and path','port and sequence','addresses and TTL','MAC and checksum','voltage or light'],3);}
export function cn_headers(){return c('cn_headers','THE SAME DATA ACQUIRES A NEW HEADER AT EACH LAYER',['layer','header','payload'],[['HTTP','method, path','application bytes'],['TCP','ports, sequence','HTTP bytes'],['IP','source, destination','TCP bytes'],['Ethernet','MAC addresses','IP bytes']],2);}
export function cn_signals(){return cards('cn_signals','A SIGNAL IS NOT THE SAME THING AS A BIT',[['Analog','continuous physical value'],['Digital','chosen symbol levels'],['Bit rate','bits per second'],['Baud rate','symbols per second']],2);}
export function cn_media(){return c('cn_media','MEDIA CHANGE LOSS, DISTANCE AND DUPLEX',['medium','strength','failure'],[['copper','electrical','attenuation and interference'],['fiber','light','distance and cost'],['radio','shared spectrum','noise and contention'],['duplex','both directions','simultaneous or alternating']],0);}
export function cn_frame(){return f('cn_frame','A FRAME BOUNDS ONE LINK HOP',['preamble','header','payload','trailer'],['clock recovery','MAC addresses','IP packet','error check'],2);}
export function cn_mac(){return cards('cn_mac','MAC ADDRESSES IDENTIFY LINK INTERFACES',[['48 bits','six octets'],['Unicast','one interface'],['Multicast','selected group'],['Broadcast','all local listeners']],3);}
export function cn_errors(){return c('cn_errors','ERROR CHECKS DETECT DIFFERENT FAILURE SHAPES',['method','state','limitation'],[['parity','one added bit','weak for multiple changes'],['checksum','word sum','not cryptographic'],['CRC','polynomial remainder','detects burst patterns']],2);}
export function cn_crc(){return c('cn_crc','THE CRC REMAINDER TRAVELS WITH THE FRAME',['input','value','operation'],[['data','1101','bits to protect'],['generator','1011','polynomial bits'],['remainder','001','transmitted check'],['receiver','remainder zero','accept or reject']],3);}
export function cn_ethernet(){return cards('cn_ethernet','ETHERNET DEFINES A LOCAL FRAME CONTRACT',[['IEEE 802.3','frame format'],['Broadcast domain','who hears a broadcast'],['Collision domain','who contends together'],['Full duplex','separate send and receive']],3);}
export function cn_devices(){return cards('cn_devices','DEVICES DIFFER BY THE ADDRESS THEY INTERPRET',[['Hub','repeats the signal'],['Bridge','joins link segments'],['Switch','forwards by MAC'],['Router','forwards by IP'],['Gateway','boundary translation or service']],3);}
export function cn_switch(){return f('cn_switch','LEARNING TURNS SOURCE MACS INTO FORWARDING STATE',['frame arrives','learn source','lookup destination','forward or flood'],['port 1 has A','CAM[A]=1','known B uses port 2','unknown B uses local ports'],2);}
export function cn_vlan(){
  const d=canvas('cn_vlan','A TRUNK CARRIES DISTINCT BROADCAST DOMAINS',290);
  d.box(30,65,250,65,'VLAN 10 membership',{fill:C.accSoft,stroke:C.acc});
  d.box(360,65,250,65,'VLAN 20 membership',{fill:C.card,stroke:C.ink2});
  d.box(155,195,330,55,'802.1Q trunk: both tagged memberships',{fill:C.card,stroke:C.ink2});
  d.arrow(155,136,245,189,{stroke:C.acc});d.arrow(485,136,395,189,{stroke:C.gray});
  d.text(320,162,'No ordinary layer-2 broadcast crosses between VLANs.',{cls:'sm'});
  return d.svg();
}
export function cn_arp(){return lanes('cn_arp','ARP FINDS THE NEXT HOP MAC, NOT A REMOTE SERVER','Finch','gateway',[[1,'ARP request: who has 192.168.10.65?'],[-1,'ARP reply: gateway MAC'],[1,'frame carries remote-destination IP packet']],'remote destination, local neighbour');}
export function cn_ipv4(){return c('cn_ipv4','A /26 SETS NETWORK AND HOST BITS',['field','value','calculation'],[['network','192.168.10.64','masked prefix'],['client','192.168.10.70','inside host range'],['broadcast','192.168.10.127','last address'],['hosts','62','64 minus network and broadcast']],1);}
export function cn_subnet(){return c('cn_subnet','SUBNETTING CHANGES THE PREFIX, THEN RECOUNTS HOSTS',['prefix','addresses','ordinary / special'],Object.entries(N.subnets).map(([p,v])=>['/'+p,String(v.addresses),p==='31'?'2 point-to-point':p==='32'?'1 host route':String(v.ordinary_hosts)]),4);}
export function cn_public_private(){return cards('cn_public_private','ADDRESS SCOPE CHANGES WHAT A ROUTER MAY REACH',[['Private','RFC 1918 local use'],['Loopback','127.0.0.1 on this host'],['Link-local','local-link fallback'],['0.0.0.0','unspecified or all local binds'],['Public','globally routed scope']],0);}
export function cn_dhcp(){return lanes('cn_dhcp','DORA BUILDS A HOST CONFIGURATION','client','DHCP server',[[1,'Discover'],[-1,'Offer address and options'],[1,'Request chosen offer'],[-1,'Acknowledge lease']],'address, mask, gateway, DNS, lease');}
export function cn_nat(){return c('cn_nat','PAT REWRITES THE FLOW AND REMEMBERS THE RETURN',['side','source','destination'],[['inside','192.168.10.70:51000','203.0.113.20:443'],['gateway','198.51.100.7:40001','203.0.113.20:443'],['return','203.0.113.20:443','198.51.100.7:40001'],['restore','gateway table','192.168.10.70:51000']],2);}
export function cn_ipv4_header(){return cards('cn_ipv4_header','TTL MAKES A PACKET FINITE',[['Version','IPv4 header'],['Total length','packet byte count'],['TTL','decrement per router'],['Protocol','TCP, UDP or ICMP'],['Checksum','header corruption check']],2);}
export function cn_ipv6(){return cards('cn_ipv6','IPV6 EXPANDS THE ADDRESS SPACE AND CHANGES DISCOVERY',[['128 bits','address size'],['Unicast','one interface'],['Multicast','group delivery'],['Link-local','neighbour scope'],['SLAAC','router-advertised setup']],0);}
export function cn_routing(){return c('cn_routing','LONGEST PREFIX MATCH CHOOSES THE MOST SPECIFIC ROUTE',['route','match','choice'],[['10.0.0.0/8','10.1.2.50','candidate'],['10.1.0.0/16','10.1.2.50','more specific'],['10.1.2.0/24','10.1.2.50','chosen'],['default','everything else','fallback']],2);}
export function cn_protocols(){return cards('cn_protocols','ROUTING PROTOCOLS STORE DIFFERENT KNOWLEDGE',[['RIP','distance vector'],['OSPF','link state and Dijkstra'],['BGP','path vector and policy'],['Default route','last resort']],2);}
export function cn_icmp(){return lanes('cn_icmp','ICMP REPORTS NETWORK CONDITIONS','host','router',[[1,'Echo Request'],[-1,'Echo Reply'],[1,'TTL expires'],[-1,'Time Exceeded']],'control message, not application payload');}
