import { cards, ledger, flow } from '../lib/fundamentals-figures.js';
import numbers from '../data/fundamentals/numbers.json' with { type: 'json' };
const n = numbers.dbms;
export function dbms_replica_ack() { return ledger('dbms_replica_ack', 'ILLUSTRATIVE ACKNOWLEDGEMENT BOUNDARIES', ['Policy', 'Wait condition', 'Acknowledgement'], [['asynchronous', 'local persistence', `${n.async_ack_ms} ms`], ['synchronous', 'all required persistence', `${n.sync_ack_ms} ms`], ['extra wait', '12 - 5', `${n.sync_penalty_ms} ms`]], 1); }
export function dbms_reshard() { return flow('dbms_reshard', 'COPYING DATA AND TRANSFERRING AUTHORITY ARE SEPARATE', ['snapshot copy', 'capture changes', 'catch up', 'fence old owner', 'route new writes', 'retire old copy'], ['defined source position', 'retain intervening writes', 'reach handoff position', 'reject stale generation', 'new owner admits', 'after recovery obligations'], 3); }
export function dbms_access_models() { return cards('dbms_access_models', 'CHOOSE FROM THE REQUIRED ACCESS PATH', [['relational', 'constraints, joins and flexible queries'], ['document', 'read and update an aggregate'], ['key-value', 'direct lookup by known key'], ['wide-column', 'partition-key ordered access'], ['graph', 'traverse connected relationships'], ['time-series', 'time-bounded ingestion and aggregation']], 0); }
export function dbms_booking_design() { return flow('dbms_booking_design', 'A BOOKING CONNECTS PHYSICAL SEATS TO A SHOW', ['venue + seat', 'event + show', 'show_seat', 'booking_item', 'booking + user', 'payment attempt'], ['physical identity', 'dated performance', 'exclusive inventory state', 'claimed inventory reference', 'owner and submit identity', 'external outcome tracked'], 2); }
export function dbms_pg_versions() { return ledger('dbms_pg_versions', 'TUPLE VISIBILITY IS NOT JUST A CURRENT FLAG', ['Tuple state', 'Reader snapshot', 'Result'], [['old visible version', 'before committed update', 'old seat state'], ['new committed version', 'after update visible', 'new seat state'], ['obsolete dead version', 'no reader can need it', 'VACUUM can reclaim']], 2); }
export function dbms_pg_plan() { return ledger('dbms_pg_plan', 'ILLUSTRATIVE ESTIMATE ERROR CHANGES PLAN REASONING', ['Measurement', 'Calculation', 'Result'], [['estimated rows', '800 × 0.02', n.estimated_rows], ['actual rows', 'counted fixture rows', n.actual_rows], ['estimate error', '80 / 16', `${n.estimate_error} times`]], 2); }
export function dbms_pool_budget() { return ledger('dbms_pool_budget', 'ILLUSTRATIVE POOLS MUST FIT THE GLOBAL SERVER LIMIT', ['Configuration', 'Calculation', 'Connections'], [['unbounded app plan', '8 × 20', n.global_pool_connections], ['application allowance', '80 - 16 reserve', n.pool_available], ['bounded per instance', '8 × 8', n.bounded_pool_connections]], 2); }
export function dbms_query_trace() { return flow('dbms_query_trace', 'ONE RESERVATION THROUGH THE DATABASE', ['parse + bind', 'plan + index', 'buffer + tuple', 'lock + validate', 'update + booking', 'WAL + commit'], ['schema and permission', 'select access path', 'snapshot visibility', 'seat still available', 'one local transaction', 'durable acknowledgement'], 3); }
export function dbms_booking_race() { return ledger('dbms_booking_race', 'THE SECOND BUYER MUST RECHECK AFTER WAITING', ['Buyer', 'Seat state', 'Outcome'], [['Ada first', 'free, locked', 'claim and commit'], ['Bo waits', 'Ada owns row lock', 'no independent claim'], ['Bo resumes', 'held after recheck', 'zero rows updated']], 2); }
export function dbms_complete_bytes() { return ledger('dbms_complete_bytes', 'ILLUSTRATIVE INVENTORY STORAGE RECONCILES EXACTLY', ['Structure', 'Page count', 'Bytes'], [['heap', n.heap_pages, n.heap_bytes], ['index', n.index_pages, n.index_bytes], ['one copy total', n.heap_pages + n.index_pages, n.inventory_with_index_bytes], ['three copies', (n.heap_pages + n.index_pages) * n.replicas, n.replicated_inventory_bytes]], 2); }
export function dbms_component_jobs() { return cards('dbms_component_jobs', 'EACH DATABASE COMPONENT MAKES A DISTINCT PROMISE', [['schema + constraints', 'legal identities and references'], ['planner + executor', 'find and compute requested rows'], ['index + buffer manager', 'locate keys and reuse pages'], ['locks + visibility', 'control competing effects and observations'], ['WAL + recovery', 'preserve acknowledged state after RAM loss'], ['replication + ownership', 'copies, failover and valid writer']], 4); }
