import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_kafka(stage=99) { return systemMap("sd_kafka", ["Topics, partitions and records", "Producers and brokers", "Replication, ISR, high watermark", "Consumers, offsets and semantics", "Consumer groups and rebalancing", "Idempotence and transactions", "Retention, compaction and replay", "Operating Kafka: KRaft and lag", "Case study: one score event"], stage); }
export function cover_sd_kafka() { return systemCover("sd_kafka", 9, ["Apache", "Kafka"], "Apache Kafka", ["Topics, partitions and records", "Producers and brokers", "Replication, ISR, high watermark", "Consumers, offsets and semantics", "Consumer groups and rebalancing", "Idempotence and transactions", "Retention, compaction and replay", "Operating Kafka: KRaft and lag", "Case study: one score event"]); }
export function sd_kafka_01() { return systemFigure("sd_kafka_01", "ONE EVENT, INDEPENDENT READERS", "rows", [["score event", "retained once", "independent history"], ["projector", "own progress", "can replay"], ["notifications", "different progress", "continues"]], ""); }
export function sd_kafka_02() { return systemFigure("sd_kafka_02", "RECORDS, KEYS, AND TOPICS", "rows", [["record", "key + value", "headers + time"], ["topic", "partition set", "policy"], ["consumer", "schema interpretation", "version aware"]], ""); }
export function sd_kafka_03() { return systemFigure("sd_kafka_03", "PARTITIONS AND ORDERING SCOPE", "rows", [["topic", "four partitions", "separate logs"], ["balanced input", "20 / 4", "five events/s each"], ["order", "within partition", "not across topic"]], ""); }
export function sd_kafka_04() { return systemFigure("sd_kafka_04", "THE RETAINED WORKLOAD", "rows", [["daily", "1,728,000 events", "345,600,000 bytes"], ["seven days", "time assumption", "logical history"], ["three copies", "7,257,600,000 bytes", "before overhead"]], ""); }
export function sd_kafka_05() { return systemFigure("sd_kafka_05", "BOOTSTRAP METADATA AND LEADER ROUTING", "rows", [["bootstrap", "discover cluster", "initial address"], ["metadata", "partition leader", "advertised route"], ["produce", "target leader", "refresh on change"]], ""); }
export function sd_kafka_06() { return systemFigure("sd_kafka_06", "BATCHING, COMPRESSION, AND DELAY", "rows", [["records", "partition buffer", "bounded memory"], ["batch", "size / delay rule", "optional compression"], ["send", "bounded request", "delivery deadline"]], ""); }
export function sd_kafka_07() { return systemFigure("sd_kafka_07", "SEGMENT APPEND AND OFFSET ASSIGNMENT", "rows", [["append", "100, 101, 102, 103", "assigned offsets"], ["local end", "104", "next position"], ["segment", "bytes + indexes", "restart validation"]], ""); }
export function sd_kafka_08() { return systemFigure("sd_kafka_08", "LOG START, END, AND VISIBLE BOUNDARIES", "rows", [["retained range", "start 100", "end 104"], ["replicated boundary", "103 exclusive", "100 to 102 visible"], ["consumer restart", "own committed offset", "separate state"]], ""); }
export function sd_kafka_09() { return systemFigure("sd_kafka_09", "LEADER, FOLLOWERS, AND ISR", "rows", [["leader", "next 104", "latest local tail"], ["follower A", "next 104", "caught up"], ["follower B", "next 103", "one behind"], ["minimum", "103", "visibility boundary"]], ""); }
export function sd_kafka_10() { return systemFigure("sd_kafka_10", "ACKNOWLEDGEMENTS AND MINIMUM ISR", "rows", [["copies", "three configured", "current ISR matters"], ["strong policy", "acks all, minimum two", "reject below minimum"], ["weaker policy", "leader ack only", "different loss window"]], ""); }
export function sd_kafka_11() { return systemFigure("sd_kafka_11", "THE HIGH WATERMARK", "rows", [["before", "104, 104, 103", "watermark 103"], ["catch up", "104, 104, 104", "reported progress"], ["after", "watermark 104", "records below visible"]], ""); }
export function sd_kafka_12() { return systemFigure("sd_kafka_12", "LEADER FAILOVER AND DIVERGENT TAILS", "rows", [["old leader", "unreplicated tail", "fails"], ["selection", "eligible history", "new epoch"], ["reconcile", "truncate / fetch as required", "safe source"]], ""); }
export function sd_kafka_13() { return systemFigure("sd_kafka_13", "FETCH POSITION AND DURABLE COMMIT", "rows", [["fetched", "100 and 101", "position 102"], ["effects complete", "both safe", "commit 102"], ["restart", "begin 102", "earlier effects preserved"]], ""); }
export function sd_kafka_14() { return systemFigure("sd_kafka_14", "AT-MOST-ONCE THROUGH COMMIT FIRST", "rows", [["commit first", "next 102", "before effect"], ["crash", "effects absent", "progress survives"], ["restart", "starts 102", "100 and 101 lost"]], ""); }
export function sd_kafka_15() { return systemFigure("sd_kafka_15", "AT-LEAST-ONCE THROUGH EFFECT FIRST", "rows", [["effect first", "100 and 101 applied", "commit still 100"], ["crash", "effect exists", "progress behind"], ["restart", "records repeat", "effect dedup needed"]], ""); }
export function sd_kafka_16() { return systemFigure("sd_kafka_16", "EXTERNAL DATABASES AND DEDUPLICATION", "rows", [["DB transaction", "source identity + effect", "one local commit"], ["Kafka progress", "later commit", "separate authority"], ["replay", "identity exists", "no second effect"]], ""); }
export function sd_kafka_17() { return systemFigure("sd_kafka_17", "CONSUMER GROUPS AND INDEPENDENT APPLICATIONS", "rows", [["projector group", "four partitions", "shared progress"], ["six members", "four active", "two idle"], ["notification group", "same source", "independent progress"]], ""); }
export function sd_kafka_18() { return systemFigure("sd_kafka_18", "HEARTBEATS, POLLING, AND FAILURE DETECTION", "rows", [["process alive", "heartbeats may continue", "work can stall"], ["progress contract", "poll / renewal", "bounded batch"], ["suspicion", "assignment changes", "old work may remain"]], ""); }
export function sd_kafka_19() { return systemFigure("sd_kafka_19", "REBALANCE AND OBSOLETE WORK", "rows", [["old member", "work in flight", "partition revoked"], ["new member", "starts committed position", "possible replay"], ["old completion", "generation obsolete", "outside effect protected"]], ""); }
export function sd_kafka_20() { return systemFigure("sd_kafka_20", "PARALLELISM, SKEW, AND CONTIGUOUS PROGRESS", "rows", [["work", "102 pending", "103 complete"], ["unsafe", "commit 104", "would skip 102"], ["safe", "wait / track prefix", "advance when complete"]], ""); }
export function sd_kafka_21() { return systemFigure("sd_kafka_21", "IDEMPOTENT PRODUCER SEQUENCES", "rows", [["first batch", "sequence 0", "base offset 100"], ["retry", "same sequence 0", "no new append"], ["new batch", "sequence 1", "new intent"]], ""); }
export function sd_kafka_22() { return systemFigure("sd_kafka_22", "TRANSACTIONAL IDENTITY AND PRODUCER FENCING", "rows", [["old owner", "epoch 8", "paused"], ["restart owner", "epoch 9", "current"], ["old resumes", "older epoch", "fenced"]], ""); }
export function sd_kafka_23() { return systemFigure("sd_kafka_23", "ATOMIC KAFKA OUTPUT AND CONSUMED OFFSETS", "rows", [["transaction", "Kafka outputs", "consumed offsets"], ["commit", "both Kafka sides", "visible together"], ["outside DB", "not included by default", "own protection"]], ""); }
export function sd_kafka_24() { return systemFigure("sd_kafka_24", "LAST STABLE OFFSET AND COMMITTED READS", "rows", [["replication boundary", "103 exclusive", "record 102 replicated"], ["open transaction", "starts at 102", "not resolved"], ["stable boundary", "102 exclusive", "committed reader waits"]], ""); }
export function sd_kafka_25() { return systemFigure("sd_kafka_25", "TIME AND SIZE RETENTION", "rows", [["old segment", "offsets 0 to 999", "policy eligible"], ["next segment", "starts 1,000", "retained"], ["slow reader", "requested deleted position", "reset / rebuild"]], ""); }
export function sd_kafka_26() { return systemFigure("sd_kafka_26", "COMPACTION AND KEYED STATE", "rows", [["key history", "old value", "new value"], ["compact", "superseded removed", "offset gaps remain"], ["delete key", "tombstone", "bounded retention"]], ""); }
export function sd_kafka_27() { return systemFigure("sd_kafka_27", "REPLAYING A PROJECTION", "rows", [["new store", "replay retained source", "isolated effects"], ["catch-up", "spare capacity", "checkpoint"], ["cutover", "required version + checks", "serve new view"]], ""); }
export function sd_kafka_28() { return systemFigure("sd_kafka_28", "SCHEMA EVOLUTION IN OLD HISTORY", "rows", [["old record", "earlier schema", "still retained"], ["new reader", "compatible interpretation", "tested"], ["three versions", "schema / aggregate / offset", "different jobs"]], ""); }
export function sd_kafka_29() { return systemFigure("sd_kafka_29", "KRAFT METADATA AND DATA REPLICATION", "rows", [["metadata", "controller consensus", "ownership decisions"], ["data", "partition replication", "record bytes"], ["clients", "metadata refresh", "target brokers"]], ""); }
export function sd_kafka_30() { return systemFigure("sd_kafka_30", "DISK, NETWORK, AND SKEW BUDGETS", "rows", [["ingress", "producer bytes", "batch work"], ["replication", "follower traffic", "copy work"], ["egress", "each consumer application", "independent reads"], ["recovery", "catch-up shares resources", "spare capacity"]], ""); }
export function sd_kafka_31() { return systemFigure("sd_kafka_31", "LAG, BACKPRESSURE, AND POISON RECORDS", "rows", [["source", "available position", "grows"], ["consumer", "retries poison record", "effects stall"], ["policy", "bounded pause / quarantine", "visible gap"]], ""); }
export function sd_kafka_32() { return systemFigure("sd_kafka_32", "PERMISSIONS, QUOTAS, AND SAFE OPERATIONS", "rows", [["identity", "authenticated client", "not all permissions"], ["ACL", "topic actions", "least required scope"], ["quota", "bounded resource use", "noisy client containment"]], ""); }
export function sd_kafka_33() { return systemFigure("sd_kafka_33", "COMPLETE SUCCESS: SOURCE TO PROJECTION", "rows", [["source commit", "score + outbox", "durable acceptance"], ["Kafka append", "key + replicas", "produce ack"], ["projection", "effect safe", "commit next offset"]], ""); }
export function sd_kafka_34() { return systemFigure("sd_kafka_34", "COMPLETE CRASH: LOST PRODUCE ACKNOWLEDGEMENT", "rows", [["broker", "batch appended", "reply lost"], ["relay restart", "outbox still pending", "may republish"], ["consumer", "same domain identity", "effect once"]], ""); }
export function sd_kafka_35() { return systemFigure("sd_kafka_35", "COMPLETE CATCH-UP CALCULATION", "rows", [["pause", "20 \u00d7 10", "200 records"], ["recovery", "100 - 20", "80 spare/s"], ["drain", "200 / 80", "2.5 s"]], ""); }
export function sd_kafka_36() { return systemFigure("sd_kafka_36", "WHEN KAFKA IS JUSTIFIED AND WHEN IT IS NOT", "rows", [["queue need", "one delayed task", "simple execution"], ["log need", "independent readers", "retained replay"], ["decision", "same requirement contract", "operations cost"]], ""); }
