import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_reliability(stage=99) { return systemMap("sd_reliability", ["Availability and SPOFs", "Redundancy, active-active, passive", "Graceful degradation and fault tolerance", "Retries, exponential backoff, and jitter", "Timeouts, circuit breakers, bulkheads", "Health checks and failover", "Disaster recovery, RTO, and RPO", "Case study: one incident"], stage); }
export function cover_sd_reliability() { return systemCover("sd_reliability", 11, ["Reliability and", "fault tolerance"], "Reliability and fault tolerance", ["Availability and SPOFs", "Redundancy, active-active, passive", "Graceful degradation and fault tolerance", "Retries, exponential backoff, and jitter", "Timeouts, circuit breakers, bulkheads", "Health checks and failover", "Disaster recovery, RTO, and RPO", "Case study: one incident"]); }
export function sd_reliability_dependency() { return systemFigure("sd_reliability_dependency", "A SHARED REQUIRED DEPENDENCY DEFEATS EVERY REPLICA", "tree", ["one score database", "application A", "application B", "application C"], "spare callers cannot repair required state"); }
export function sd_reliability_success() { return systemFigure("sd_reliability_success", "REACHABLE DOES NOT IMPLY A SUCCESSFUL OPERATION", "rows", [["reachable", "connection works", "necessary"], ["correct", "right authorized score", "necessary"], ["timely", "inside deadline", "necessary"], ["successful", "all required conditions", "counted"]], "count the user's outcome"); }
export function sd_reliability_availability() { return systemFigure("sd_reliability_availability", "ILLUSTRATIVE THIRTY-DAY UNAVAILABLE-TIME BUDGET", "bars", [["99.9%", 2592, "s"], ["99.99%", 259.2, "s"]], "state the interval before the percentage"); }
export function sd_reliability_series() { return systemFigure("sd_reliability_series", "ILLUSTRATIVE INDEPENDENT REQUIRED PATH", "rows", [["proxy", "0.999", "required"], ["application", "0.999", "required"], ["database", "0.999", "required"], ["product", "0.997002999", "path"]], "a percentage belongs to the whole path"); }
export function sd_reliability_parallel() { return systemFigure("sd_reliability_parallel", "ALTERNATIVE PATHS NEED THE SAME REQUIRED CAPABILITY", "split", [["path A", "authorized read\nrequired fresh state"], ["path B", "authorized read\nrequired fresh state"]], "alternative means sufficient"); }
export function sd_reliability_common() { return systemFigure("sd_reliability_common", "SEPARATE PROCESSES CAN SHARE ONE FAILURE CAUSE", "tree", ["shared configuration", "zone A app", "zone B app", "zone C app"], "move the cause, not only the box"); }
export function sd_reliability_survivor() { return systemFigure("sd_reliability_survivor", "ILLUSTRATIVE CAPACITY BEFORE AND AFTER A REPLICA LOSS", "rows", [["normal", "4 x 350", "1,400 req/s"], ["peak demand", "1,000", "250 per replica"], ["one lost", "3 x 350", "1,050 req/s"], ["survivors", "1,000 / 3", "333.333... each"]], "surviving capacity carries the promise"); }
export function sd_reliability_regions() { return systemFigure("sd_reliability_regions", "TRAFFIC OWNERSHIP AND WRITE OWNERSHIP ARE SEPARATE", "split", [["active-active", "both serve reads\nwrite rule still required"], ["active-passive", "one owns writes\nstandby must be promotable"]], "explain who can commit"); }
export function sd_reliability_uncertain() { return systemFigure("sd_reliability_uncertain", "FAILURE AFTER COMMIT LEAVES AN UNCERTAIN CLIENT", "sequence", {"actors": ["scorer", "application", "database"], "steps": [[0, 1, "command K"], [1, 2, "commit effect + K"], [1, 0, "reply lost"], [0, 1, "retry K"], [1, 0, "recover committed result"]]}, "correctness survives the lost reply"); }
export function sd_reliability_degraded() { return systemFigure("sd_reliability_degraded", "OPTIONAL WORK MUST NOT OWN THE CORE RESPONSE", "fan", {"source": "score read", "targets": ["fresh score: required", "recommendations: optional", "age-labeled cached mode"]}, "degrade the feature, preserve permission"); }
export function sd_reliability_inflight() { return systemFigure("sd_reliability_inflight", "ILLUSTRATIVE SLOWDOWN EXPANDS IN-FLIGHT WORK", "bars", [["0.2 s mean", 200, "requests"], ["2 s mean", 2000, "requests"]], "waiting has a resource cost"); }
export function sd_reliability_cascade() { return systemFigure("sd_reliability_cascade", "MORE LOAD CAN MAKE LESS USEFUL WORK COMPLETE", "flow", ["replica lost", "peers slow", "deadlines miss", "retries add load"], "remove the feedback before reopening"); }
export function sd_reliability_drain() { return systemFigure("sd_reliability_drain", "ILLUSTRATIVE BACKLOG RECOVERY COUNTS NEW ARRIVALS", "rows", [["capacity", "800 jobs/s", "processing"], ["arrivals", "600 jobs/s", "new work"], ["net drain", "200 jobs/s", "800 - 600"], ["backlog", "12,000 jobs", "60 seconds"]], "recovery uses spare capacity"); }
export function sd_reliability_classes() { return systemFigure("sd_reliability_classes", "FAILURE CLASSIFICATION COMES BEFORE RETRY POLICY", "rows", [["invalid request", "permanent", "fix request"], ["peer unavailable", "possibly transient", "bounded attempt"], ["reply lost", "outcome uncertain", "recover same command"]], "another attempt needs the same purpose"); }
export function sd_reliability_backoff() { return systemFigure("sd_reliability_backoff", "ILLUSTRATIVE RETRY CEILINGS DOUBLE", "rows", [["attempt index", "0", "1", "2", "3"], ["ceiling ms", "100", "200", "400", "800"], ["purpose", "short fault", "more recovery", "less pressure", "bounded wait"]], "a delay cap is not a total deadline"); }
export function sd_reliability_jitter() { return systemFigure("sd_reliability_jitter", "IDENTICAL CEILINGS DO NOT REQUIRE IDENTICAL RETRY TIMES", "split", [["fixed backoff", "every caller waits 400 ms\nthen callers return together"], ["full jitter", "each caller samples 0 to 400 ms\nexpected delay is 200 ms"]], "spread attempts and bound their count"); }
export function sd_reliability_amplification() { return systemFigure("sd_reliability_amplification", "ILLUSTRATIVE ATTEMPT COUNTS MULTIPLY", "flow", ["1 operation", "3 gateway", "9 service", "27 database"], "choose one semantic retry owner"); }
export function sd_reliability_retrybudget() { return systemFigure("sd_reliability_retrybudget", "ILLUSTRATIVE ORIGINAL AND RETRY DEMAND", "rows", [["original", "1,000 req/s", "user work"], ["retry budget", "100 req/s", "10% of originals"], ["exhausted", "no more retries", "return outcome"]], "recovery work has its own admission rule"); }
export function sd_reliability_deadline() { return systemFigure("sd_reliability_deadline", "ILLUSTRATIVE USEFUL BUDGET SHRINKS ALONG THE PATH", "rows", [["whole request", "500 ms", "outer budget"], ["reserves", "40 + 60 ms", "400 ms useful"], ["already spent", "120 ms", "280 ms remains"]], "preserve time for the reply"); }
export function sd_reliability_timeoutcommit() { return systemFigure("sd_reliability_timeoutcommit", "A CALLER TIMEOUT AND A COMMIT CAN BOTH HAPPEN", "sequence", {"actors": ["caller", "service", "database"], "steps": [[0, 1, "start command K"], [1, 2, "begin write"], [1, 0, "deadline expires"], [2, 1, "commit K completes"], [0, 1, "recover result for K"]]}, "query the effect under its original identity"); }
export function sd_reliability_breaker() { return systemFigure("sd_reliability_breaker", "THE BREAKER LIMITS CALLS WHILE EVIDENCE CHANGES", "flow", ["closed: calls", "failure rule", "open: no calls", "half-open: probes"], "successful probes reopen the path"); }
export function sd_reliability_probes() { return systemFigure("sd_reliability_probes", "A RECOVERY PROBE IS NOT A FULL TRAFFIC RESTART", "rows", [["open", "ordinary calls rejected", "cooldown"], ["half-open", "bounded probes", "measure progress"], ["healthy", "increase admitted work", "close"], ["failing", "stop probes", "reopen"]], "reopen gradually"); }
export function sd_reliability_bulkhead() { return systemFigure("sd_reliability_bulkhead", "ILLUSTRATIVE RESOURCE PARTITION DURING A CLIP STALL", "rows", [["total", "100 slots", "shared budget"], ["clip maximum", "20 slots", "bounded failure"], ["other work", "80 slots", "still available"]], "reserve what must remain useful"); }
export function sd_reliability_checks() { return systemFigure("sd_reliability_checks", "DIFFERENT PROBES TRIGGER DIFFERENT ACTIONS", "rows", [["startup", "initialization done?", "begin checking"], ["liveness", "process progressing?", "restart if needed"], ["readiness", "can accept new work?", "route or drain"], ["user probe", "operation succeeds?", "measure promise"]], "probe the capability you route on"); }
export function sd_reliability_detection() { return systemFigure("sd_reliability_detection", "ILLUSTRATIVE DETECTION POLICY BEFORE ROUTING CHANGE", "rows", [["probe interval", "5 seconds", "assumed"], ["failure threshold", "3 consecutive", "assumed"], ["modeled detection", "15 seconds", "3 x 5"], ["then", "remove new work", "drain admitted work"]], "removal and termination are separate"); }
export function sd_reliability_failover() { return systemFigure("sd_reliability_failover", "ILLUSTRATIVE FAILOVER CRITICAL PATH", "rows", [["detect", "15 seconds", "failure evidence"], ["promote", "10 seconds", "safe ownership"], ["route", "5 seconds", "new destination"], ["total", "30 seconds", "serial sum"]], "recovery includes state and routing"); }
export function sd_reliability_failovertrace() { return systemFigure("sd_reliability_failovertrace", "THE CANDIDATE MUST BECOME SAFE BEFORE NEW WRITES", "sequence", {"actors": ["router", "candidate", "state store"], "steps": [[0, 1, "stop old route"], [1, 2, "recover authoritative state"], [1, 2, "acquire fenced authority"], [1, 0, "ready for writes"], [0, 1, "send new commands"]]}, "readiness follows recovery"); }
export function sd_reliability_fence() { return systemFigure("sd_reliability_fence", "AUTHORITY MUST BE CHECKED AT THE EFFECT BOUNDARY", "rows", [["old owner", "older token", "late write"], ["new owner", "newer token", "current write"], ["state store", "reject older", "accept current"]], "a local timer cannot revoke a remote writer"); }
export function sd_reliability_backup() { return systemFigure("sd_reliability_backup", "A REPLICA AND A RECOVERY COPY HAVE DIFFERENT JOBS", "split", [["replica", "tracks current changes\nmay copy deletion"], ["recovery copy", "preserves earlier state\nrestore under separate authority"]], "recovery must survive the destructive cause"); }
export function sd_reliability_rto() { return systemFigure("sd_reliability_rto", "ILLUSTRATIVE RESTORATION AGAINST A 600 SECOND RTO", "rows", [["prepare", "60 seconds", "replacement"], ["restore", "180 seconds", "state"], ["verify + route", "120 seconds", "service"], ["sum", "360 seconds", "240 seconds margin"]], "include verification before calling it restored"); }
export function sd_reliability_rpo() { return systemFigure("sd_reliability_rpo", "ILLUSTRATIVE SNAPSHOT GAP BECOMES AN EVENT COUNT", "rows", [["recoverable gap", "300 seconds", "assumed"], ["write workload", "20 events/s", "Heron"], ["potential loss", "6,000 events", "300 x 20"]], "count recoverable acknowledged effects"); }
export function sd_reliability_lagloss() { return systemFigure("sd_reliability_lagloss", "ILLUSTRATIVE ASYNCHRONOUS LAG EXPOSURE", "rows", [["lag", "2 seconds", "assumed"], ["writes", "20 events/s", "constant model"], ["missing state", "40 events", "2 x 20"]], "replicated later is not acknowledged elsewhere now"); }
export function sd_reliability_drill() { return systemFigure("sd_reliability_drill", "A DRILL CHECKS A SERVICE, NOT ONLY A BACKUP FILE", "flow", ["restore data", "replay history", "verify invariants", "serve safely"], "practice the path before the incident"); }
export function sd_reliability_normal() { return systemFigure("sd_reliability_normal", "ILLUSTRATIVE NORMAL CAPACITY AND ADMISSION", "rows", [["workers", "4 x 350", "1,400 req/s"], ["peak", "1,000 req/s", "400 spare"], ["clip calls", "20 slots max", "isolated"], ["commands", "stable identity", "commit evidence"]], "write the normal contract first"); }
export function sd_reliability_hedge() { return systemFigure("sd_reliability_hedge", "ILLUSTRATIVE HEDGES USE ALL POST-FAILURE HEADROOM", "rows", [["survivor capacity", "1,050 req/s", "3 x 350"], ["original demand", "1,000 req/s", "peak"], ["5% extra attempts", "50 req/s", "hedged reads"], ["total demand", "1,050 req/s", "no margin"]], "tail improvement still consumes work"); }
export function sd_reliability_canary() { return systemFigure("sd_reliability_canary", "ILLUSTRATIVE LIMITED RETURN TO TRAFFIC", "rows", [["peak", "1,000 req/s", "original demand"], ["recovered canary", "50 req/s", "5% share"], ["established path", "950 req/s", "remaining share"], ["then", "inspect outcome", "increase gradually"]], "success at a small share is evidence"); }
export function sd_reliability_jobs() { return systemFigure("sd_reliability_jobs", "ONE JOB PER RELIABILITY MECHANISM", "rows", [["admission + bulkhead", "bound resources", "useful work"], ["deadline + retry", "bound recovery attempts", "same identity"], ["health + fencing", "route and own safely", "no obsolete writes"], ["backup + restore", "recover state", "verify before serve"]], "name the guarantee each box preserves"); }
export function sd_reliability_budgetcard() { return systemFigure("sd_reliability_budgetcard", "CHECK CAPACITY, RECOVERY TIME, AND DATA SEPARATELY", "matrix", {"rows": ["worker loss", "regional restore", "snapshot gap"], "cols": ["computed quantity", "illustrative result"], "values": [["3 x 350", "1,050 req/s"], ["60 + 180 + 120", "360 s"], ["300 x 20", "6,000 events"]]}, "availability is not a data-loss guarantee"); }

export function sd_reliability_breaker_numeric() { return systemFigure('sd_reliability_breaker_numeric','ILLUSTRATIVE BREAKER EVIDENCE AND RECOVERY', 'rows', [['window','12 failures / 20','0.6 failure fraction'],['open','time 5 seconds','threshold 10 failures'],['cooldown','30 seconds','probe at time 35'],['half-open','2 probes maximum','both pass or reopen']], 'probes need their own admission bound'); }
