import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_rate_limiting(stage=99) { return systemMap("sd_rate_limiting", ["Rate limiting requirements", "Fixed window counter", "Sliding window log", "Sliding window counter", "Token bucket", "Leaky bucket", "Distributed limiting with Redis", "Case study: the complete limiter"], stage); }
export function cover_sd_rate_limiting() { return systemCover("sd_rate_limiting", 12, ["Rate", "limiting"], "Rate limiting", ["Rate limiting requirements", "Fixed window counter", "Sliding window log", "Sliding window counter", "Token bucket", "Leaky bucket", "Distributed limiting with Redis", "Case study: the complete limiter"]); }
export function sd_rate_limiting_contract() { return systemFigure("sd_rate_limiting_contract", "THE SAME WORDS CAN NAME DIFFERENT POLICIES", "split", [["trailing-window limit", "no more than 100 accepted\nin every trailing 60 seconds"], ["burst-capable rate", "refill at 100 / 60 per second\nburst capacity chosen separately"]], "a minute needs a boundary rule"); }
export function sd_rate_limiting_identity() { return systemFigure("sd_rate_limiting_identity", "CLIENT INPUT BECOMES A POLICY KEY ONLY AFTER VALIDATION", "flow", ["client request", "trusted identity", "policy dimension", "state key"], "name who owns the key"); }
export function sd_rate_limiting_dimensions() { return systemFigure("sd_rate_limiting_dimensions", "DIFFERENT LIMITS COUNT DIFFERENT THINGS", "rows", [["rate", "accepted cost over time", "arrival demand"], ["concurrency", "in-flight work", "occupied resources"], ["quota", "cumulative allocation", "accounting budget"]], "define the counted resource"); }
export function sd_rate_limiting_boundary() { return systemFigure("sd_rate_limiting_boundary", "EARLY PROTECTION AND TRUSTED USER POLICY HAVE DIFFERENT INPUTS", "flow", ["coarse edge rule", "authenticate", "user admission", "application work"], "reject before the expensive effect"); }
export function sd_rate_limiting_fixed() { return systemFigure("sd_rate_limiting_fixed", "ILLUSTRATIVE BUCKET STATE AT A MINUTE BOUNDARY", "rows", [["before boundary", "bucket 0", "counter can be full"], ["at 60 seconds", "bucket 1", "fresh counter"], ["same identity", "new bucket key", "new allowance"]], "the bucket chooses which history matters"); }
export function sd_rate_limiting_boundaryburst() { return systemFigure("sd_rate_limiting_boundaryburst", "ILLUSTRATIVE FIXED-WINDOW BOUNDARY BURST", "rows", [["time 59.9 s", "100 requests", "old bucket"], ["time 60.1 s", "100 requests", "new bucket"], ["short span", "200 in 0.2 s", "1,000 req/s"]], "local bucket correctness is not a moving limit"); }
export function sd_rate_limiting_countsemantics() { return systemFigure("sd_rate_limiting_countsemantics", "ATTEMPT ACCOUNTING AND ACCEPTED-WORK ACCOUNTING DIFFER", "split", [["count attempts", "increment every checked request\nreject when result exceeds limit"], ["count admissions", "check available allowance\nincrement only if accepted"]], "name what the counter means"); }
export function sd_rate_limiting_expiry() { return systemFigure("sd_rate_limiting_expiry", "TWO COMMANDS LEAVE A CRASH GAP", "sequence", {"actors": ["gateway", "Redis", "next gateway"], "steps": [[0, 1, "increment new key"], [1, 0, "counter created"], [0, 1, "crash before expire"], [2, 1, "find retained old state"], [2, 1, "atomic cleanup rule needed"]]}, "command atomicity is not procedure atomicity"); }
export function sd_rate_limiting_log() { return systemFigure("sd_rate_limiting_log", "THE MOVING INTERVAL RETAINS RECENT ACCEPTED ARRIVALS", "rows", [["expire", "timestamp <= t - T", "remove"], ["retain", "timestamp > t - T", "count"], ["admit", "retained count < limit", "append unique event"]], "count the interval you promised"); }
export function sd_rate_limiting_logtrace() { return systemFigure("sd_rate_limiting_logtrace", "ILLUSTRATIVE LOG BEFORE AND AFTER CLEANUP", "rows", [["before", "0, 10, 40, 59", "accepted times"], ["cutoff at t=60", "remove 0", "left endpoint"], ["retained", "10, 40, 59", "count 3"], ["after admission", "10, 40, 59, 60", "count 4"]], "cleanup precedes counting"); }
export function sd_rate_limiting_interval() { return systemFigure("sd_rate_limiting_interval", "ENDPOINT RULES DECIDE AN EXACT BOUNDARY EVENT", "split", [["left endpoint", "time t - T\nexcluded in this chapter"], ["right endpoint", "time t\nincluded for accepted work"]], "compare with the same inequalities"); }
export function sd_rate_limiting_memory() { return systemFigure("sd_rate_limiting_memory", "ILLUSTRATIVE STATE ACCOUNTING FOR ACTIVE SUBJECTS", "rows", [["subjects", "100,000", "assumed"], ["log entries", "10,000,000", "100 each"], ["log simplified bytes", "240,000,000", "24 per event"], ["counter simplified bytes", "3,200,000", "32 per subject"]], "precision retains more history"); }
export function sd_rate_limiting_oldest() { return systemFigure("sd_rate_limiting_oldest", "THE OLDEST RETAINED EVENT DETERMINES THE NEXT POSSIBLE SLOT", "flow", ["log full", "oldest time", "add interval", "advisory retry"], "advice is not a booking"); }
export function sd_rate_limiting_counter() { return systemFigure("sd_rate_limiting_counter", "TWO BUCKETS APPROXIMATE A MOVING INTERVAL", "rows", [["previous bucket", "C_previous", "weight 1 - f"], ["current bucket", "C_now", "full weight"], ["estimated recent", "C_now + weighted previous", "admission estimate"]], "overlap in time is not exact overlap in events"); }
export function sd_rate_limiting_countertrace() { return systemFigure("sd_rate_limiting_countertrace", "ILLUSTRATIVE INTERPOLATION WITH THE SAME COUNTS", "rows", [["previous / current", "80 / 30", "stored"], ["15 seconds elapsed", "30 + 80 x 0.75", "90"], ["30 seconds elapsed", "30 + 80 x 0.5", "70"]], "the approximation forgets placement"); }
export function sd_rate_limiting_countererror() { return systemFigure("sd_rate_limiting_countererror", "SAME COUNTERS CAN REPRESENT DIFFERENT EXACT HISTORIES", "split", [["older arrivals clustered late", "true retained previous can be 80\ntrue total 110, estimate 90"], ["older arrivals clustered early", "many previous events expired\nestimate can overcount"]], "small state changes the guarantee"); }
export function sd_rate_limiting_rollover() { return systemFigure("sd_rate_limiting_rollover", "BUCKET IDENTITY DISAMBIGUATES ROLLOVER AND INACTIVITY", "rows", [["same bucket", "keep current", "count admission"], ["next bucket", "current becomes previous", "start current"], ["long idle gap", "old overlap is gone", "clear old counts"]], "an old count needs its old time"); }
export function sd_rate_limiting_token() { return systemFigure("sd_rate_limiting_token", "REFILL THEN SPEND FROM A BOUNDED BALANCE", "flow", ["stored balance + time", "elapsed refill", "cap at B", "debit if enough"], "capacity controls bursts, rate controls replenishment"); }
export function sd_rate_limiting_tokentrace() { return systemFigure("sd_rate_limiting_tokentrace", "ILLUSTRATIVE TOKEN STATE AFTER EACH STEP", "rows", [["initial", "100 tokens", "t=0"], ["spend 80", "20 tokens", "same time"], ["wait 6 seconds", "30 tokens", "refill 10"], ["spend 15", "15 tokens", "need 3 s for cost 20"]], "show the state before deciding"); }
export function sd_rate_limiting_tokenwait() { return systemFigure("sd_rate_limiting_tokenwait", "ILLUSTRATIVE REJECTION DELAY FROM A DEFICIT", "rows", [["requested cost", "20", "tokens"], ["available", "15", "tokens"], ["deficit", "5", "tokens"], ["wait", "5 / (100 / 60)", "3 seconds"]], "rejection preserves the unspent balance"); }
export function sd_rate_limiting_tokenbound() { return systemFigure("sd_rate_limiting_tokenbound", "ILLUSTRATIVE TOKEN-BUCKET ACCOUNTING BOUND", "rows", [["saved allowance", "100 tokens", "capacity"], ["60 s refill", "100 tokens", "r x duration"], ["upper cost bound", "200 tokens", "sum"]], "say which bound the policy promises"); }
export function sd_rate_limiting_costs() { return systemFigure("sd_rate_limiting_costs", "ILLUSTRATIVE WEIGHTED REQUEST COSTS", "rows", [["first operation", "20 tokens", "20 spent"], ["second", "30 tokens", "50 spent total"], ["third", "50 tokens", "100 spent total"], ["next cost 1", "101 total", "reject"]], "cost belongs in the atomic comparison"); }
export function sd_rate_limiting_shape() { return systemFigure("sd_rate_limiting_shape", "SHAPING CHANGES WHEN ACCEPTED WORK LEAVES", "flow", ["bursty arrivals", "bounded queue", "paced release", "downstream work"], "output pacing requires an owner"); }
export function sd_rate_limiting_leaktrace() { return systemFigure("sd_rate_limiting_leaktrace", "ILLUSTRATIVE SHAPING WAIT BEFORE EXECUTION", "rows", [["cost ahead", "20 jobs", "equal cost"], ["release rate", "100 / 60 jobs/s", "assumed"], ["queue delay", "12 seconds", "20 / rate"], ["processing", "not counted", "additional time"]], "admission can still miss the user's deadline"); }
export function sd_rate_limiting_virtual() { return systemFigure("sd_rate_limiting_virtual", "ILLUSTRATIVE VIRTUAL BACKLOG TRANSLATES COST TO TIME", "rows", [["reserved future cost", "30 units", "debt"], ["service rate", "100 / 60 units/s", "policy"], ["future interval", "18 seconds", "30 / rate"]], "virtual state still needs an atomic owner"); }
export function sd_rate_limiting_compare() { return systemFigure("sd_rate_limiting_compare", "EACH ALGORITHM PRESERVES A DIFFERENT POLICY DETAIL", "rows", [["fixed / counter", "cheap state", "boundary / estimate"], ["sliding log", "exact recent arrivals", "history cost"], ["token bucket", "burst plus rate", "saved allowance"], ["leaky shaping", "paced output", "bounded waiting"]], "match the guarantee before choosing storage"); }
export function sd_rate_limiting_race() { return systemFigure("sd_rate_limiting_race", "ILLUSTRATIVE SEPARATE READS DOUBLE-SPEND THE LAST SLOT", "rows", [["initial", "99 accepted", "one slot"], ["A reads", "99", "decides allow"], ["B reads", "99", "decides allow"], ["both increment", "101", "too many allowed"]], "serialize the decision, not just the arithmetic"); }
export function sd_rate_limiting_script() { return systemFigure("sd_rate_limiting_script", "ONE SERIALIZED TOKEN DECISION", "flow", ["read + validate", "refill + cap", "check cost", "store + return"], "script state has a defined transition"); }
export function sd_rate_limiting_atomiclimits() { return systemFigure("sd_rate_limiting_atomiclimits", "LOCAL ATOMICITY AND RECOVERY DURABILITY ARE DIFFERENT", "split", [["same serving Redis", "script cannot interleave\none serialized decision"], ["replica or failover", "may recover older allowance\nseparate durability question"]], "do not widen the guarantee silently"); }
export function sd_rate_limiting_dimensionshared() { return systemFigure("sd_rate_limiting_dimensionshared", "ONE REQUEST MAY NEED SEVERAL POLICY DECISIONS", "fan", {"source": "trusted request", "targets": ["user budget", "tenant budget", "endpoint budget"]}, "a partial debit needs a policy"); }
export function sd_rate_limiting_hotkey() { return systemFigure("sd_rate_limiting_hotkey", "USER SHARDING DOES NOT DISTRIBUTE A GLOBAL TENANT COUNTER", "tree", ["one tenant budget", "user key A", "user key B", "user key C"], "locate the shared serialization point"); }
export function sd_rate_limiting_fallback() { return systemFigure("sd_rate_limiting_fallback", "ILLUSTRATIVE LOCAL FALLBACK CHANGES THE GLOBAL RULE", "rows", [["4 local full budgets", "4 x 100", "400 allowed"], ["4 partitioned budgets", "4 x 25", "100 allowed total"], ["trade-off", "unused local shares", "lower utilization"]], "fallback must state its new bound"); }
export function sd_rate_limiting_accepted() { return systemFigure("sd_rate_limiting_accepted", "A TRUSTED REQUEST PASSES ONE SHARED ADMISSION DECISION", "sequence", {"actors": ["gateway", "limiter", "application"], "steps": [[0, 1, "trusted subject + admission ID"], [1, 0, "allow and append once"], [0, 2, "execute under deadline"], [2, 0, "return operation outcome"]]}, "admission precedes the expensive effect"); }
export function sd_rate_limiting_reject() { return systemFigure("sd_rate_limiting_reject", "ILLUSTRATIVE TOKEN REJECTION ADVICE", "rows", [["required", "1 token", "cost"], ["available", "0.5 token", "balance"], ["deficit", "0.5 token", "missing"], ["refill-only delay", "0.3 seconds", "deficit / rate"]], "clients still need bounded retries"); }
export function sd_rate_limiting_tests() { return systemFigure("sd_rate_limiting_tests", "TEST THE POLICY'S BOUNDARIES RATHER THAN ONLY THE HAPPY PATH", "rows", [["concurrent final token", "one allows", "next rejects"], ["clock rollback", "no added credit", "time retained"], ["window cutoff", "endpoint rule", "matching cleanup"], ["failover state", "possible lost debit", "declared guarantee"]], "state what a recovered counter can forget"); }
export function sd_rate_limiting_totals() { return systemFigure("sd_rate_limiting_totals", "ILLUSTRATIVE SHARED LIMITER WORKLOAD AND STATE", "rows", [["base checks", "1,000/s", "3 mean in flight"], ["3 dimensions", "3,000 ops/s", "before retries"], ["exact log events", "10,000,000", "100,000 users"], ["simplified log bytes", "240,000,000", "24 per event"]], "count round trips, events, and hot keys"); }
export function sd_rate_limiting_jobs() { return systemFigure("sd_rate_limiting_jobs", "ONE JOB PER ADMISSION COMPONENT", "rows", [["identity boundary", "establish subject", "prevent forged keys"], ["algorithm state", "implement interval", "chosen semantics"], ["atomic owner", "serialize debit", "prevent double spend"], ["failure policy", "bound unavailable behavior", "protect service"]], "every box needs a named guarantee"); }
