import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_storage(stage=99) { return systemMap("sd_storage", ["Local, block, file, object storage", "Buckets, objects and metadata", "Presigned URLs and direct upload", "Multipart uploads", "Checksums and integrity", "Replication and distributed file systems", "Lifecycle and retention", "Case study: the media upload path"], stage); }
export function cover_sd_storage() { return systemCover("sd_storage", 13, ["Storage", "systems"], "Storage systems", ["Local, block, file, object storage", "Buckets, objects and metadata", "Presigned URLs and direct upload", "Multipart uploads", "Checksums and integrity", "Replication and distributed file systems", "Lifecycle and retention", "Case study: the media upload path"]); }
export function sd_storage_local() { return systemFigure("sd_storage_local", "A WORKER PATH DOES NOT DEFINE A DURABLE PUBLIC OBJECT", "flow", ["worker writes file", "worker replaced", "new worker", "recover elsewhere"], "follow the lifetime of the owner"); }
export function sd_storage_block() { return systemFigure("sd_storage_block", "ILLUSTRATIVE ROUND-UP TO BLOCK BOUNDARIES", "rows", [["logical bytes", "5,000,000,000", "payload"], ["block size", "4,096 bytes", "assumed"], ["blocks", "1,220,704", "round upward"], ["allocated", "5,000,003,584", "3,584 padding"]], "interface and physical allocation differ"); }
export function sd_storage_file() { return systemFigure("sd_storage_file", "A FILE INTERFACE ADDS NAMES AND COORDINATED OPERATIONS", "tree", ["shared filesystem", "directory lookup", "file ranges", "locks and rename"], "a path promises more than raw blocks"); }
export function sd_storage_interfaces() { return systemFigure("sd_storage_interfaces", "CHOOSE THE CONTRACT NEEDED BY THE WORKLOAD", "rows", [["block", "addressed bytes", "filesystem or database above"], ["file", "paths and file operations", "namespace semantics"], ["object", "keyed complete objects", "object API"], ["database", "structured facts", "queries and transactions"]], "name the operations before the vendor"); }
export function sd_storage_address() { return systemFigure("sd_storage_address", "OBJECT ADDRESS AND APPLICATION ID HAVE DIFFERENT OWNERS", "rows", [["bucket", "heron-media", "storage namespace"], ["key", "tenant-a/clips/c7/source-v1", "stored bytes"], ["database ID", "clip c7", "permission and state"], ["version", "immutable source identity", "publication target"]], "identity locates bytes, policy permits access"); }
export function sd_storage_immutable() { return systemFigure("sd_storage_immutable", "PUBLICATION CHANGES A POINTER, NOT THE OLD BYTES", "rows", [["old object", "source-v1", "remains stable"], ["new object", "source-v2", "upload and verify"], ["metadata pointer", "v1 becomes v2", "atomic DB change"], ["old readers", "still read v1", "same bytes"]], "stable byte identity simplifies recovery"); }
export function sd_storage_metabytes() { return systemFigure("sd_storage_metabytes", "ILLUSTRATIVE METADATA AND MEDIA SIZING", "rows", [["clip records", "3,000", "100 x 30"], ["metadata payload", "1,500,000 B", "500 each"], ["media payload", "15,000,000,000,000 B", "5 GB each"]], "the small control record owns the large object"); }
export function sd_storage_consistency() { return systemFigure("sd_storage_consistency", "AN OBJECT GUARANTEE DOES NOT COVER THE DATABASE POINTER", "split", [["object operation", "completed object visibility\nper documented storage semantics"], ["application publication", "metadata + object relationship\nseparate coordination protocol"]], "keep the boundaries explicit"); }
export function sd_storage_paths() { return systemFigure("sd_storage_paths", "CONTROL AND BULK BYTES FOLLOW DIFFERENT PATHS", "split", [["metadata", "client -> application -> database\npermission and reserved identity"], ["media bytes", "client -> object service\nscoped delegated upload"]], "authorize small state, transfer large bytes directly"); }
export function sd_storage_signed() { return systemFigure("sd_storage_signed", "DELEGATED ACCESS IS NARROWER THAN GENERAL STORAGE CREDENTIALS", "flow", ["authenticate uploader", "reserve private key", "sign narrow request", "storage validates"], "the URL grants what its signer can grant"); }
export function sd_storage_expiry() { return systemFigure("sd_storage_expiry", "ILLUSTRATIVE CREDENTIAL AND TRANSFER BUDGETS", "rows", [["requested URL lifetime", "3,600 s", "chosen"], ["credential remaining", "1,200 s", "underlying limit"], ["effective simplified lifetime", "1,200 s", "minimum"], ["upload planning budget", "600 s", "500 s transfer + 100 margin"]], "a new retry needs still-valid authority"); }
export function sd_storage_states() { return systemFigure("sd_storage_states", "AN UPLOAD RESERVATION IS NOT PUBLICATION", "flow", ["pending", "uploaded", "verified", "published"], "advance only after checking the state"); }
export function sd_storage_completion() { return systemFigure("sd_storage_completion", "THE APPLICATION VERIFIES THE RESERVED OBJECT", "sequence", {"actors": ["client", "application", "object service"], "steps": [[0, 1, "initiate upload"], [1, 0, "reserved key + signed access"], [0, 2, "upload bytes"], [0, 1, "request completion"], [1, 2, "check exact object attributes"]]}, "publication follows verified storage evidence"); }
export function sd_storage_parts() { return systemFigure("sd_storage_parts", "ILLUSTRATIVE INCLUSIVE PART RANGES", "rows", [["first", "0 to 99,999,999", "100,000,000 B"], ["second", "100,000,000 to 199,999,999", "100,000,000 B"], ["last", "4,900,000,000 to 4,999,999,999", "100,000,000 B"]], "no gap and no duplicate byte"); }
export function sd_storage_manifest() { return systemFigure("sd_storage_manifest", "COMPLETION ASSEMBLES ONE EXPLICIT UPLOAD SESSION", "sequence", {"actors": ["client", "storage", "application"], "steps": [[0, 1, "create multipart session"], [1, 0, "upload ID"], [0, 1, "numbered parts + checksums"], [0, 1, "ordered completion manifest"], [0, 2, "verify completed object"]]}, "assembled bytes still need publication checks"); }
export function sd_storage_retry() { return systemFigure("sd_storage_retry", "ILLUSTRATIVE RETRANSMISSION PAYLOAD AFTER ONE FAILURE", "bars", [["one failed part", 100000000, "B"], ["whole object", 5000000000, "B"]], "retry the failed boundary"); }
export function sd_storage_parallel() { return systemFigure("sd_storage_parallel", "ILLUSTRATIVE PARALLEL PARTS SHARE ONE LINK", "rows", [["concurrent parts", "5", "assumed"], ["per-part rate", "2,000,000 B/s", "even share"], ["group transfer", "500,000,000 B", "50 seconds"], ["50 parts", "10 groups", "500 seconds"]], "count the bottleneck once"); }
export function sd_storage_abandoned() { return systemFigure("sd_storage_abandoned", "ILLUSTRATIVE UNFINISHED-PART STORAGE", "rows", [["one session", "2 parts", "200,000,000 B"], ["ten sessions", "20 parts", "2,000,000,000 B"], ["cleanup", "abort stale sessions", "after resume horizon"]], "unfinished bytes have a lifetime too"); }
export function sd_storage_digest() { return systemFigure("sd_storage_digest", "COMPUTED CHECKSUMS DISTINGUISH SAME-LENGTH PAYLOADS", "rows", [["payload A", "Heron:7:120", "11 bytes"], ["payload B", "Heron:7:121", "11 bytes"], ["SHA-256 prefixes", "5eae8f64 / 09a87f96", "different"], ["CRC32", "4221786988 / 2359585786", "different"]], "verify the full intended checksum"); }
export function sd_storage_binding() { return systemFigure("sd_storage_binding", "EXPECTED CONTENT MUST BE ATTACHED TO THE RESERVED IDENTITY", "flow", ["reserve expectation", "upload exact identity", "storage validates", "check reservation"], "a new client claim cannot rewrite the expectation"); }
export function sd_storage_etag() { return systemFigure("sd_storage_etag", "A VALIDATOR AND A FULL-CONTENT CHECKSUM HAVE DIFFERENT CONTRACTS", "split", [["entity validator", "conditional representation checks\nproduct-defined ETag"], ["integrity checksum", "specified algorithm and byte scope\ncompare expected full value"]], "a familiar field name is not a hash proof"); }
export function sd_storage_range() { return systemFigure("sd_storage_range", "ILLUSTRATIVE RANGE RETRIEVAL AND CHECKSUM SCOPE", "rows", [["object", "5,000,000,000 B", "whole checksum"], ["range", "1,000,000 B", "0.02% of object"], ["ideal transfer", "0.1 seconds", "10,000,000 B/s"], ["proof", "range alone insufficient", "whole checksum"]], "retrieved bytes define what can be checked"); }
export function sd_storage_replication() { return systemFigure("sd_storage_replication", "ILLUSTRATIVE THREE-COPY PAYLOAD BUDGET", "tree", ["5 GB logical", "copy A: 5 GB", "copy B: 5 GB", "copy C: 5 GB"], "copy count needs a failure domain"); }
export function sd_storage_erasure() { return systemFigure("sd_storage_erasure", "ILLUSTRATIVE FOUR-DATA TWO-PARITY ACCOUNTING", "rows", [["logical payload", "5,000,000,000 B", "4 data shards"], ["one shard", "1,250,000,000 B", "logical / 4"], ["6 shards", "7,500,000,000 B", "1.5 x logical"], ["required available", "4 shards", "code assumption"]], "space saving changes repair work"); }
export function sd_storage_dfs() { return systemFigure("sd_storage_dfs", "NAMESPACE COORDINATION AND PAYLOAD TRANSFER HAVE DIFFERENT OWNERS", "split", [["metadata coordinator", "file name -> piece locations\nownership and namespace"], ["data servers", "store and serve pieces\nreplicate and repair"]], "the coordinator need not proxy every byte"); }
export function sd_storage_region() { return systemFigure("sd_storage_region", "RECOVERY NEEDS BOTH CONTENT AND ITS VERIFIED REFERENCE", "flow", ["local object complete", "remote copy verified", "metadata recoverable", "publish recovered"], "a pointer is useful only with its object"); }
export function sd_storage_remote() { return systemFigure("sd_storage_remote", "ILLUSTRATIVE EVENT GAP IS A DIFFERENT WORKLOAD FROM MEDIA", "rows", [["score rate", "20 events/s", "shared baseline"], ["gap", "5 seconds", "assumed"], ["score exposure", "100 events", "computed"], ["media exposure", "object-specific", "measure completion"]], "do not reuse a lag number across workloads"); }
export function sd_storage_lifecycle() { return systemFigure("sd_storage_lifecycle", "ILLUSTRATIVE THIRTY-DAY MEDIA RETENTION", "rows", [["daily media", "100 x 5 GB", "500,000,000,000 B"], ["hot 7 days", "700 clips", "3,500,000,000,000 B"], ["other 23 days", "2,300 clips", "11,500,000,000,000 B"], ["all 30 days", "3,000 clips", "15,000,000,000,000 B"]], "retention creates the steady population"); }
export function sd_storage_archive() { return systemFigure("sd_storage_archive", "RETAINED AND IMMEDIATELY RETRIEVABLE ARE DIFFERENT STATES", "flow", ["archived object", "request restore", "wait + verify", "issue playback access"], "storage existence is not playback readiness"); }
export function sd_storage_deletion() { return systemFigure("sd_storage_deletion", "APPLICATION DELETION AND BYTE CLEANUP HAVE SEPARATE COMMITS", "sequence", {"actors": ["application", "database", "storage"], "steps": [[0, 1, "commit delete state + identities"], [0, 1, "stop new playback authorization"], [0, 2, "delete recorded objects"], [2, 0, "cleanup outcome"], [0, 1, "mark cleanup complete"]]}, "record exactly which bytes are being removed"); }
export function sd_storage_reconcile() { return systemFigure("sd_storage_reconcile", "DIFFERENT STRANDED STATES NEED DIFFERENT RECOVERY", "matrix", {"rows": ["pending + parts", "complete + pending", "deleted + bytes"], "cols": ["evidence", "action"], "values": [["resume horizon", "resume or abort"], ["verified object", "publish or reclaim"], ["tombstone IDs", "idempotent delete"]]}, "recover by identity and state"); }
export function sd_storage_fullupload() { return systemFigure("sd_storage_fullupload", "THE CONTROL PATH OWNS PUBLICATION WHILE STORAGE OWNS BYTES", "flow", ["reserve + authorize", "direct multipart transfer", "verify + process", "publish metadata"], "publication is the final controlled transition"); }
export function sd_storage_ownership() { return systemFigure("sd_storage_ownership", "ONE JOB PER MEDIA COMPONENT", "rows", [["application", "permission + upload state", "control path"], ["database", "relationships + publication", "queryable facts"], ["object service", "immutable bytes + attributes", "bulk path"], ["worker", "verify and derive outputs", "recoverable processing"]], "separate responsibilities by actual state"); }
export function sd_storage_retrycomplete() { return systemFigure("sd_storage_retrycomplete", "LOST COMPLETION REPLY RECOVERS THE SAME IDENTITY", "sequence", {"actors": ["client", "application", "storage"], "steps": [[0, 1, "complete upload c7"], [1, 2, "verify reserved object"], [1, 0, "reply lost"], [0, 1, "retry completion c7"], [1, 0, "return existing verified state"]]}, "no new upload is needed to resolve an old one"); }
export function sd_storage_baseline() { return systemFigure("sd_storage_baseline", "SHARED RECORD AND EVENT STORAGE ARE DIFFERENT MODELS", "rows", [["daily records", "4,320,000,000 B", "8,640,000 x 500"], ["30-day records", "129,600,000,000 B", "before copies"], ["3 copies", "388,800,000,000 B", "record model"], ["30-day events", "10,368,000,000 B", "20 x 200 x seconds"]], "retain originals, transmit deliveries"); }
export function sd_storage_mediabudget() { return systemFigure("sd_storage_mediabudget", "ILLUSTRATIVE ONE-OBJECT BUDGET DEPENDS ON THE STORAGE MODEL", "rows", [["logical upload", "5,000,000,000 B", "50 parts"], ["3 full copies", "15,000,000,000 B", "replication model"], ["4 + 2 coding", "7,500,000,000 B", "coding model"], ["proxy traffic", "10,000,000,000 B", "ingress + egress"]], "compare like units and alternative designs"); }
export function sd_storage_final() { return systemFigure("sd_storage_final", "EACH BOUNDARY HAS A DISTINCT VERIFICATION QUESTION", "matrix", {"rows": ["permission", "transfer", "publication", "recovery"], "cols": ["question", "evidence"], "values": [["who may upload?", "trusted reservation"], ["same intended bytes?", "length + checksum"], ["playable now?", "verified state"], ["survives fault?", "copies + restore test"]]}, "say what each boundary proves"); }
