import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_realtime(stage=99) { return systemMap("sd_realtime", ["Real-time requirements, ordering", "Polling and long polling", "SSE and WebSockets", "Connections, heartbeats, presence", "Pub/sub to WebSocket gateways", "Fan-out and slow consumers", "Reconnect and replay", "Client state and acknowledgements", "Case study: live score updates"], stage); }
export function cover_sd_realtime() { return systemCover("sd_realtime", 16, ["Real-time", "systems"], "Real-time systems", ["Real-time requirements, ordering", "Polling and long polling", "SSE and WebSockets", "Connections, heartbeats, presence", "Pub/sub to WebSocket gateways", "Fan-out and slow consumers", "Reconnect and replay", "Client state and acknowledgements", "Case study: live score updates"]); }
export function sd_realtime_promise() { return systemFigure("sd_realtime_promise", "COMMITTED STATE IS NOT DISPLAYED STATE", "flow", ["score commit", "event delivery", "client reducer", "screen update"], "Follow the screen too"); }
export function sd_realtime_versions() { return systemFigure("sd_realtime_versions", "IDENTITY, ORDER, AND PAYLOAD", "rows", [["event", "id=a", "version=101", "score=120"], ["next event", "id=b", "version=102", "score=121"], ["late repeat", "id=a", "version=101", "ignore"]], "A late message is not newer"); }
export function sd_realtime_state_delta() { return systemFigure("sd_realtime_state_delta", "TWO PAYLOADS, DIFFERENT RECOVERY", "split", [["Replacement", "version 102\nscore = 121"], ["Delta", "version 102\nadd 1 after version 101"]], "Know what can be skipped"); }
export function sd_realtime_latency() { return systemFigure("sd_realtime_latency", "THE BUDGET IS SPENT AT EACH STAGE", "rows", [["validate + commit", "5 ms", "10 ms"], ["publish + dispatch", "5 ms", "15 ms"], ["client apply", "5 ms", "total 40 ms"]], "Measure the user boundary"); }
export function sd_realtime_poll() { return systemFigure("sd_realtime_poll", "THE UPDATE WAITS FOR THE NEXT CHECK", "timeline", {"events": [[0, "poll old score"], [1, "score changes"], [5, "poll new score"]], "end": 5}, "Empty checks still cost work"); }
export function sd_realtime_longpoll() { return systemFigure("sd_realtime_longpoll", "WAIT WITHOUT LOSING THE NEXT VERSION", "sequence", {"actors": ["Client", "Score service", "Wait registry"], "steps": [[0, 1, "after version 101"], [1, 2, "register waiter"], [1, 2, "recheck progress"], [2, 1, "version 102 ready"], [1, 0, "respond, then repeat"]]}, "The cursor closes the gap"); }
export function sd_realtime_pollrace() { return systemFigure("sd_realtime_pollrace", "RESPONSE ARRIVAL IS NOT SOURCE ORDER", "sequence", {"actors": ["Client", "Slow request", "Fast request"], "steps": [[0, 1, "request A"], [0, 2, "request B"], [2, 0, "version 102: apply"], [1, 0, "version 101: reject"]]}, "Compare the state version"); }
export function sd_realtime_push() { return systemFigure("sd_realtime_push", "REQUEST CHECKS AND EVENT DELIVERIES", "split", [["Polling", "10,000 checks/s\n20,000,000 payload B/s"], ["Every-event push", "1,000,000 deliveries/s\n200,000,000 payload B/s"]], "Compare equal product semantics"); }
export function sd_realtime_sse() { return systemFigure("sd_realtime_sse", "TEXT LINES MAKE ONE DISPATCHED EVENT", "rows", [["identity", "id: 102"], ["type", "event: score"], ["payload", "data: score 121"], ["boundary", "blank line", "dispatch"]], "The blank line is a boundary"); }
export function sd_realtime_websocket() { return systemFigure("sd_realtime_websocket", "OPEN, THEN EXCHANGE FRAMED MESSAGES", "sequence", {"actors": ["Client", "Gateway"], "steps": [[0, 1, "opening handshake"], [1, 0, "upgrade accepted"], [0, 1, "subscribe match"], [1, 0, "score version 102"], [0, 1, "application ack"]]}, "The socket is a transport"); }
export function sd_realtime_frames() { return systemFigure("sd_realtime_frames", "PAYLOAD IS NOT THE COMPLETE WIRE COST", "rows", [["server message", "200 payload B", "4 header B", "204 B"], ["client message", "200 payload B", "8 header B", "208 B"], ["not included", "TLS", "transport", "IP"]], "Count the chosen boundary"); }
export function sd_realtime_subscription() { return systemFigure("sd_realtime_subscription", "AUTHORIZE BEFORE ADDING MEMBERSHIP", "flow", ["authenticate peer", "validate topic", "check permission", "register subscriber"], "A connection is not permission"); }
export function sd_realtime_gateways() { return systemFigure("sd_realtime_gateways", "FIVE OWNERS HOLD THE CONNECTIONS", "fan", {"source": "50,000 viewers", "targets": ["gateway A: 10,000", "gateway B: 10,000", "gateway C: 10,000", "gateway D/E: 20,000"]}, "Connections have an owner"); }
export function sd_realtime_heartbeat() { return systemFigure("sd_realtime_heartbeat", "OBSERVE A RESPONSE, THEN EXPIRE SILENCE", "sequence", {"actors": ["Gateway", "Viewer"], "steps": [[0, 1, "ping with identity"], [1, 0, "pong same payload"], [0, 1, "next ping"], [0, 0, "deadline: no response"]]}, "Liveness is observed communication"); }
export function sd_realtime_drain() { return systemFigure("sd_realtime_drain", "STOP NEW OWNERSHIP, THEN RELEASE OLD LINES", "flow", ["remove admissions", "notify clients", "jitter reconnect", "close by deadline"], "A restart is a traffic event"); }
export function sd_realtime_presence() { return systemFigure("sd_realtime_presence", "A LEASE BOUNDS STALE ONLINE STATE", "timeline", {"events": [[0, "renew"], [30, "renew"], [60, "link lost"], [120, "last lease expires"]], "end": 120}, "Online is a declared observation"); }
export function sd_realtime_pubsub() { return systemFigure("sd_realtime_pubsub", "DURABLE SCORE, SHARED EVENT, LOCAL SOCKETS", "flow", ["scorer", "score commit", "event stream", "gateway subscribers"], "Keep scoring independent of sockets"); }
export function sd_realtime_interests() { return systemFigure("sd_realtime_interests", "SEND TO INTERESTED GATEWAYS", "matrix", {"rows": ["match red", "match blue", "match green"], "cols": ["gateway A", "gateway B", "gateway C"], "values": [["yes", "yes", "no"], ["no", "yes", "no"], ["no", "no", "yes"]]}, "Interests can change mid-event"); }
export function sd_realtime_partition_order() { return systemFigure("sd_realtime_partition_order", "ONE ORDER SCOPE, MANY DELIVERY OWNERS", "rows", [["event key", "match red", "one ordered partition"], ["processor", "one assigned owner", "route to gateways"], ["recipients", "gateway A", "gateway B", "gateway C"]], "A consumer group divides work"); }
export function sd_realtime_race() { return systemFigure("sd_realtime_race", "SNAPSHOT AND STREAM NEED A COMMON POSITION", "sequence", {"actors": ["Client", "Snapshot API", "Event log"], "steps": [[0, 2, "establish replay cursor"], [0, 1, "fetch snapshot v101"], [2, 0, "event v102 available"], [1, 0, "snapshot v101"], [0, 0, "apply events after 101"]]}, "Buffer then compare versions"); }
export function sd_realtime_fanout() { return systemFigure("sd_realtime_fanout", "THE FINAL LEG DOMINATES THIS WORKLOAD", "bars", [["broker to 5 gateways", 20000, "B/s"], ["one gateway", 40000000, "B/s"], ["all viewers", 200000000, "B/s"]], "Count recipients, not only events"); }
export function sd_realtime_batch() { return systemFigure("sd_realtime_batch", "SAVE OPERATIONS, SPEND WAITING TIME", "rows", [["events", "1", "2", "3", "4,5"], ["batch payload", "5 \u00d7 200 B", "1,000 B"], ["first-event wait", "4 / 20 s", "0.2 s"]], "A timer bounds quiet periods"); }
export function sd_realtime_slow() { return systemFigure("sd_realtime_slow", "A BUFFER DOES NOT FIX A NEGATIVE RATE BALANCE", "rows", [["produced", "4,000 B/s"], ["drained", "1,000 B/s"], ["growth", "3,000 B/s"], ["60,000 B limit", "fills in 20 s"]], "Bound every recipient queue"); }
export function sd_realtime_topics() { return systemFigure("sd_realtime_topics", "EQUAL MATCH COUNTS DO NOT MEAN EQUAL WORK", "bars", [["30,000 viewers", 600000, "deliveries/s"], ["15,000 viewers", 300000, "deliveries/s"], ["5,000 viewers", 100000, "deliveries/s"]], "Route using work, not only counts"); }
export function sd_realtime_replay() { return systemFigure("sd_realtime_replay", "THE GAP HAS A SIZE", "rows", [["disconnect", "5 seconds"], ["input rate", "20 events/s"], ["missing history", "100 events"], ["payload", "20,000 bytes"]], "Resume from applied progress"); }
export function sd_realtime_retention() { return systemFigure("sd_realtime_retention", "EXPIRED HISTORY REQUIRES A NEW BASE", "timeline", {"events": [[0, "old cursor"], [30, "retained start"], [60, "current head"]], "end": 60}, "A tail needs a valid base"); }
export function sd_realtime_snapshot_tail() { return systemFigure("sd_realtime_snapshot_tail", "REPLACE THE BASE, THEN APPLY THE TAIL", "sequence", {"actors": ["Client", "Source", "Replay log"], "steps": [[0, 1, "request state"], [1, 0, "snapshot at v200"], [0, 2, "events after v200"], [2, 0, "v201, v202"], [0, 0, "apply contiguous tail"]]}, "Version the snapshot"); }
export function sd_realtime_reconnect() { return systemFigure("sd_realtime_reconnect", "SPREAD ATTEMPTS AND ENFORCE CAPACITY", "split", [["No spreading", "50,000 peers\ncorrelated attempt"], ["10-second window", "expected 5,000/s\nplus admission limit"]], "Recovery is a workload"); }
export function sd_realtime_reducer() { return systemFigure("sd_realtime_reducer", "ARRIVAL ORDER AND APPLICATION ORDER", "rows", [["arrive", "101", "102", "102", "104,103"], ["actions", "apply", "apply", "ignore", "hold then fill"], ["applied", "101", "102", "103", "104"]], "Identity is not continuity"); }
export function sd_realtime_ack() { return systemFigure("sd_realtime_ack", "ACKNOWLEDGE THE CHOSEN EFFECT", "sequence", {"actors": ["Gateway", "Client"], "steps": [[0, 1, "event 102"], [1, 1, "parse and apply"], [1, 0, "ack applied 102"], [0, 0, "release buffered prefix"]]}, "Define what ack proves"); }
export function sd_realtime_command() { return systemFigure("sd_realtime_command", "REQUEST ACTION, THEN PUBLISH ITS RESULT", "flow", ["command + op ID", "authorize + validate", "commit once", "event + version"], "Commands and events differ"); }
export function sd_realtime_correction() { return systemFigure("sd_realtime_correction", "REFERENCED HISTORY AND CURRENT ORDER", "rows", [["original", "event a", "version 101", "add 1"], ["correction", "event c", "version 103", "reverses a"], ["current order", "101", "102", "103"]], "Reference is not order"); }
export function sd_realtime_full() { return systemFigure("sd_realtime_full", "ONE ACCEPTED COMMAND, MANY VIEWER EFFECTS", "flow", ["score + outbox", "retained event", "interested gateways", "versioned reducers"], "Defend every state owner"); }
export function sd_realtime_totals() { return systemFigure("sd_realtime_totals", "EVERY MULTIPLIER HAS A MEANING", "rows", [["producer", "20 events/s", "200 B/event"], ["broker leg", "5 gateways", "100 deliveries/s"], ["one gateway", "10,000 viewers", "200,000 deliveries/s"], ["all viewers", "50,000 viewers", "1,000,000 deliveries/s"]], "One event is copied repeatedly"); }
export function sd_realtime_failure() { return systemFigure("sd_realtime_failure", "SOCKET OWNERSHIP CHANGES, SCORE HISTORY REMAINS", "sequence", {"actors": ["Viewer", "New gateway", "Event store"], "steps": [[0, 1, "reconnect after v101"], [1, 2, "authorize and replay"], [2, 1, "v102 onward"], [1, 0, "catch-up plus live"], [0, 1, "ack contiguous progress"]]}, "Test the replay transition"); }
export function sd_realtime_contract() { return systemFigure("sd_realtime_contract", "EACH FAILURE HAS AN EXPLICIT RESPONSE", "matrix", {"rows": ["duplicate", "gap", "old cursor", "slow client"], "cols": ["detect", "response"], "values": [["event ID", "ignore repeat"], ["version jump", "replay suffix"], ["retention bound", "snapshot + tail"], ["queue limit", "coalesce or close"]]}, "The failure branch is part of the design"); }
