import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_data_pipelines(stage=99) { return systemMap("sd_data_pipelines", ["OLTP vs OLAP", "Batch processing", "Stream processing", "Event time, windows, watermarks", "ETL, ELT, warehouses, and lakes", "CDC and materialized views", "Checkpoints and exactly-once", "Spark and Flink", "Case study: score to report"], stage); }
export function cover_sd_data_pipelines() { return systemCover("sd_data_pipelines", 17, ["Data", "pipelines"], "Data pipelines", ["OLTP vs OLAP", "Batch processing", "Stream processing", "Event time, windows, watermarks", "ETL, ELT, warehouses, and lakes", "CDC and materialized views", "Checkpoints and exactly-once", "Spark and Flink", "Case study: score to report"]); }
export function sd_data_pipelines_workloads() { return systemFigure("sd_data_pipelines_workloads", "THE SAME BUSINESS, DIFFERENT ACCESS PATTERNS", "split", [["OLTP", "update one match\nshort transactional work"], ["OLAP", "sum season history\nscan and aggregate"]], "Isolate work that competes"); }
export function sd_data_pipelines_column() { return systemFigure("sd_data_pipelines_column", "READ THE FIELDS THE QUESTION NEEDS", "bars", [["full rows", 500000000, "B"], ["one column", 8000000, "B"]], "Layout follows the question"); }
export function sd_data_pipelines_freshness() { return systemFigure("sd_data_pipelines_freshness", "EVERY ANSWER HAS A SOURCE BOUNDARY", "flow", ["accepted changes", "captured position", "processed position", "published total"], "Freshness is part of meaning"); }
export function sd_data_pipelines_reproduce() { return systemFigure("sd_data_pipelines_reproduce", "REBUILD AN ANSWER FROM NAMED INPUTS", "flow", ["raw accepted history", "versioned transform", "identified output", "reconciliation"], "Derived data needs a repair path"); }
export function sd_data_pipelines_batch_boundary() { return systemFigure("sd_data_pipelines_batch_boundary", "NAME THE RECORDS, NOT ONLY THE CLOCK", "rows", [["interval", "3,600 seconds"], ["input", "20 events/s", "72,000 records"], ["payload", "200 B/event", "14,400,000 B"], ["identity", "source positions", "manifest"]], "A finite set has an identity"); }
export function sd_data_pipelines_map() { return systemFigure("sd_data_pipelines_map", "EACH RECORD BECOMES A NAMED CONTRIBUTION", "rows", [["a", "red", "2"], ["b", "blue", "3"], ["c", "red", "4"], ["d", "red", "1"]], "Validate before adding"); }
export function sd_data_pipelines_shuffle() { return systemFigure("sd_data_pipelines_shuffle", "GROUP BEFORE REDUCING", "fan", {"source": "mapped pairs", "targets": ["red: [2,4,1] \u2192 7", "blue: [3] \u2192 3"], "labels": ["same key", "same key"]}, "Network work can exceed arithmetic"); }
export function sd_data_pipelines_publish_batch() { return systemFigure("sd_data_pipelines_publish_batch", "FINISH THE GENERATION BEFORE READERS SWITCH", "flow", ["write job output", "validate partitions", "commit manifest", "read new generation"], "Completion is a state change"); }
export function sd_data_pipelines_running() { return systemFigure("sd_data_pipelines_running", "THE STATE CHANGES ONE RECORD AT A TIME", "rows", [["a: red +2", "red=2", "blue=0"], ["b: blue +3", "red=2", "blue=3"], ["c: red +4", "red=6", "blue=3"], ["d: red +1", "red=7", "blue=3"]], "Earlier records leave state"); }
export function sd_data_pipelines_keyed() { return systemFigure("sd_data_pipelines_keyed", "EQUAL KEYS SHARE STATE OWNERSHIP", "tree", ["partition by team", "red owner\nsum 7", "blue owner\nsum 3", "other owners\nindependent state"], "Balance keys, not just partitions"); }
export function sd_data_pipelines_backpressure() { return systemFigure("sd_data_pipelines_backpressure", "A SLOW SINK MUST NOT CREATE UNBOUNDED MEMORY", "flow", ["retained input", "bounded source read", "operator state", "slow sink"], "Observe the oldest waiting input"); }
export function sd_data_pipelines_retraction() { return systemFigure("sd_data_pipelines_retraction", "AN UPDATE REPLACES A CONTRIBUTION", "rows", [["before", "4"], ["remove old", "-4"], ["add new", "+6"], ["net change", "+2"]], "Know whether a row is a fact or a change"); }
export function sd_data_pipelines_times() { return systemFigure("sd_data_pipelines_times", "ONE HISTORY, ANOTHER ARRIVAL ORDER", "rows", [["arrival order", "a", "b", "c", "d"], ["event times", "1", "3", "2", "7"], ["late relative to b", "c at time 2", "arrives third"]], "Choose the time question"); }
export function sd_data_pipelines_windows() { return systemFigure("sd_data_pipelines_windows", "ASSIGN BEFORE AGGREGATING", "rows", [["[0,5)", "red 2+4=6", "blue 3"], ["[5,10)", "red 1", "blue 0"], ["boundary rule", "include left", "exclude right"]], "Boundaries prevent double assignment"); }
export function sd_data_pipelines_watermark() { return systemFigure("sd_data_pipelines_watermark", "OBSERVATION PLUS POLICY PRODUCES PROGRESS", "rows", [["max observed time", "7"], ["allowed disorder", "2 seconds"], ["watermark", "7 - 2 = 5"], ["first interval", "[0,5)", "eligible by rule"]], "A watermark is not a death certificate"); }
export function sd_data_pipelines_late() { return systemFigure("sd_data_pipelines_late", "A FINALIZED WINDOW STILL NEEDS A VIOLATION RULE", "flow", ["late time=2 event", "check retained state", "update or repair", "count disposition"], "Finality must be declared"); }
export function sd_data_pipelines_etl() { return systemFigure("sd_data_pipelines_etl", "TRANSFORM BEFORE LOADING", "flow", ["extract source", "validate + transform", "load clean rows", "analytical query"], "The order names a boundary"); }
export function sd_data_pipelines_elt() { return systemFigure("sd_data_pipelines_elt", "LOAD BEFORE DERIVING TABLES", "flow", ["extract source", "controlled raw target", "versioned transform", "derived tables"], "Raw data needs governance"); }
export function sd_data_pipelines_warehouse() { return systemFigure("sd_data_pipelines_warehouse", "A FACT AND ITS DESCRIPTIVE CONTEXT", "tree", ["match_runs fact", "event ID + runs", "team dimension", "venue dimension"], "A join has a time meaning"); }
export function sd_data_pipelines_lake() { return systemFigure("sd_data_pipelines_lake", "FILES NEED A TABLE OR DATASET BOUNDARY", "flow", ["object files", "schema + catalogue", "snapshot manifest", "query readers"], "A folder is not a transaction"); }
export function sd_data_pipelines_cdc() { return systemFigure("sd_data_pipelines_cdc", "CAPTURE THE COMMIT, INCLUDING DELETES", "flow", ["source transaction", "change log", "positioned CDC", "derived target"], "A deleted row still has a change"); }
export function sd_data_pipelines_handoff() { return systemFigure("sd_data_pipelines_handoff", "ONE SOURCE VIEW, ONE CONTINUATION POSITION", "sequence", {"actors": ["Source", "Snapshot reader", "CDC consumer"], "steps": [[0, 1, "snapshot at position P"], [0, 2, "retain changes after P"], [1, 2, "load snapshot"], [0, 2, "replay suffix after P"]]}, "No unrecorded interval"); }
export function sd_data_pipelines_cdc_update() { return systemFigure("sd_data_pipelines_cdc_update", "CHANGES NEED THE PRIOR CONTRIBUTION", "rows", [["stored source key", "value 4"], ["after image", "value 6"], ["derived change", "-4 + 6", "+2"], ["delete later", "remove 6", "key gone"]], "Retain what a correction needs"); }
export function sd_data_pipelines_view() { return systemFigure("sd_data_pipelines_view", "THE VIEW IS AN ANSWER WITH PROGRESS", "rows", [["raw red", "2", "4", "1"], ["raw blue", "3"], ["materialized", "red=7", "blue=3"], ["metadata", "source position", "transform version"]], "A fast read has upstream work"); }
export function sd_data_pipelines_checkpoint() { return systemFigure("sd_data_pipelines_checkpoint", "STATE AND POSITION DESCRIBE ONE PREFIX", "rows", [["completed input", "offsets 0,1", "values 2,3"], ["checkpoint", "position 1", "state 5"], ["restored tail", "offsets 2,3", "values 4,1"], ["final state", "5 + 4 + 1", "10"]], "Restore the same prefix"); }
export function sd_data_pipelines_barrier() { return systemFigure("sd_data_pipelines_barrier", "A DISTRIBUTED PREFIX NEEDS COORDINATION", "flow", ["source positions", "barrier boundary", "operator snapshots", "completed checkpoint"], "A consistent cut is not one clock tick"); }
export function sd_data_pipelines_duplicate() { return systemFigure("sd_data_pipelines_duplicate", "A REPLAYED EXTERNAL ADDITION CAN COUNT TWICE", "rows", [["correct input", "2+3+4+1", "10"], ["replayed c", "2+3+4+4+1", "14"], ["needed rule", "effect identity", "atomic target boundary"]], "Name the effect boundary"); }
export function sd_data_pipelines_catchup() { return systemFigure("sd_data_pipelines_catchup", "DRAIN RATE SUBTRACTS NEW ARRIVALS", "rows", [["processing", "120 records/s"], ["new input", "20 records/s"], ["net drain", "100 records/s"], ["12,000 backlog", "120 seconds"]], "Capacity equals recovery ability"); }
export function sd_data_pipelines_spark() { return systemFigure("sd_data_pipelines_spark", "CONTROL AND DATA EXECUTION HAVE DIFFERENT OWNERS", "fan", {"source": "Spark driver", "targets": ["executor: input tasks", "executor: shuffle tasks", "executor: output tasks"]}, "The driver is not the whole data path"); }
export function sd_data_pipelines_stages() { return systemFigure("sd_data_pipelines_stages", "A KEY CHANGE CREATES AN EXCHANGE", "flow", ["read + map", "shuffle by team", "sum each group", "publish results"], "Final size hides intermediate work"); }
export function sd_data_pipelines_flink() { return systemFigure("sd_data_pipelines_flink", "COORDINATE A STATEFUL DATAFLOW", "fan", {"source": "Flink coordinator", "targets": ["task: source positions", "task: keyed windows", "task: compatible sink"]}, "Worker memory needs recovery"); }
export function sd_data_pipelines_choice() { return systemFigure("sd_data_pipelines_choice", "CHOOSE AN EXECUTION MODEL, THEN VERIFY CONNECTORS", "matrix", {"rows": ["bounded input", "ongoing state", "time windows", "external output"], "cols": ["question to ask", "needed proof"], "values": [["batch boundary", "repeatable input"], ["state size", "restore plan"], ["lateness policy", "tested watermark"], ["sink guarantee", "retry-safe effect"]]}, "A name is not a guarantee"); }
export function sd_data_pipelines_full() { return systemFigure("sd_data_pipelines_full", "ONE RECORD CONTRIBUTES TO NAMED VIEWS", "flow", ["commit c: red +4", "capture position", "window [0,5)", "publish red=6"], "Identify the query's grain"); }
export function sd_data_pipelines_totals() { return systemFigure("sd_data_pipelines_totals", "RAW HISTORY, PHYSICAL COPIES, AND OPERATOR STATE", "rows", [["daily input", "1,728,000 events", "345,600,000 B"], ["30 days", "logical payload", "10,368,000,000 B"], ["three copies", "physical payload", "31,104,000,000 B"], ["one-day IDs", "32 B each", "55,296,000 B"]], "Distinguish stored information"); }
export function sd_data_pipelines_backfill() { return systemFigure("sd_data_pipelines_backfill", "REPROCESSING IS A SEPARATE WORKLOAD", "rows", [["history", "7 days", "12,096,000 records"], ["assumed capacity", "2,000 records/s"], ["raw processing time", "6,048 seconds"], ["publication", "new generation", "controlled switch"]], "Rebuild into identified output"); }
export function sd_data_pipelines_contract() { return systemFigure("sd_data_pipelines_contract", "THE PIPELINE'S FAILURE RESPONSES", "matrix", {"rows": ["duplicate", "late event", "schema error", "source gap"], "cols": ["detect", "response"], "values": [["identity/version", "retry-safe effect"], ["watermark policy", "update or repair"], ["validation", "quarantine + fix"], ["capture position", "snapshot + replay"]]}, "A dropped record needs a reason"); }
