import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_security(stage=99) { return systemMap("sd_security", ["Authentication vs authorization", "Sessions and cookies", "JWT and API keys", "OAuth 2.0 and PKCE", "RBAC, ACLs, and resource policy", "Encryption and secrets", "Password hashing and signed URLs", "CORS, CSRF and abuse prevention", "Case study: securing one operation"], stage); }
export function cover_sd_security() { return systemCover("sd_security", 18, ["System", "security"], "Security", ["Authentication vs authorization", "Sessions and cookies", "JWT and API keys", "OAuth 2.0 and PKCE", "RBAC, ACLs, and resource policy", "Encryption and secrets", "Password hashing and signed URLs", "CORS, CSRF and abuse prevention", "Case study: securing one operation"]); }
export function sd_security_auth() { return systemFigure("sd_security_auth", "IDENTITY IS AN INPUT TO A PERMISSION DECISION", "flow", ["verify credential", "resolve principal", "load trusted resource", "evaluate action"], "Check the requested resource"); }
export function sd_security_tenant() { return systemFigure("sd_security_tenant", "REQUEST AND RESOURCE MUST SHARE THE ALLOWED SCOPE", "rows", [["request identity", "tenant 8"], ["stored object", "tenant 7"], ["policy", "8 \u2260 7", "deny absent sharing"]], "Scope every derived copy"); }
export function sd_security_deny() { return systemFigure("sd_security_deny", "MISSING POLICY DOES NOT BECOME A GRANT", "flow", ["action + resource", "trusted context", "explicit grant?", "allow or deny"], "Make the default visible in code"); }
export function sd_security_boundaries() { return systemFigure("sd_security_boundaries", "EVERY HOP HAS AN INPUT AND AUTHORITY CONTRACT", "flow", ["untrusted browser", "authenticated edge", "authorized app", "scoped storage"], "Internal does not mean trusted"); }
export function sd_security_session() { return systemFigure("sd_security_session", "A TOKEN REFERENCES CURRENT SERVER STATE", "sequence", {"actors": ["Browser", "App", "Session store"], "steps": [[0, 1, "successful login"], [1, 2, "create token record"], [1, 0, "set session cookie"], [0, 1, "next request + token"], [1, 2, "resolve current session"]]}, "The token is a credential"); }
export function sd_security_cookie() { return systemFigure("sd_security_cookie", "EACH ATTRIBUTE HAS A SPECIFIC JOB", "rows", [["Secure", "secure transport delivery"], ["HttpOnly", "no document.cookie read"], ["SameSite", "cross-site send policy"], ["scope", "host/domain and path"]], "A flag has a boundary"); }
export function sd_security_rotation() { return systemFigure("sd_security_rotation", "A PRE-LOGIN TOKEN DOES NOT BECOME THE LOGIN TOKEN", "rows", [["before login", "token A", "anonymous"], ["successful login", "token B", "Mira"], ["old identifier", "token A", "invalidated"]], "Rotate the reference"); }
export function sd_security_logout() { return systemFigure("sd_security_logout", "DELETE BOTH THE REFERENCE AND ITS SERVER VALIDITY", "flow", ["logout request", "invalidate record", "clear browser cookie", "reject copied token"], "A copied token outlives a browser action"); }
export function sd_security_jwt() { return systemFigure("sd_security_jwt", "DECODING DOES NOT VERIFY AUTHORITY", "rows", [["header", "allowed algorithm + key context"], ["payload", "issuer, audience, subject, times"], ["protection", "verify with trusted key"], ["application", "validate purpose then authorize"]], "Readable is not trusted"); }
export function sd_security_token_checks() { return systemFigure("sd_security_token_checks", "A GENUINE TOKEN CAN HAVE THE WRONG DESTINATION", "flow", ["verify protection", "expected issuer", "intended audience", "right purpose + times"], "Valid for whom and for what"); }
export function sd_security_lifetime() { return systemFigure("sd_security_lifetime", "LOCAL VALIDATION NEEDS A REVOCATION POLICY", "timeline", {"events": [[0, "issue token"], [1, "permission removed"], [300, "token expires"]], "end": 300}, "Stateless verification has a policy cost"); }
export function sd_security_keys() { return systemFigure("sd_security_keys", "CALLER CREDENTIAL AND ISSUER CAPABILITY", "split", [["API key", "authorizes a caller\nscope and revoke it"], ["Signing key", "protects issued tokens\nverify through trusted keys"]], "Keys grant different powers"); }
export function sd_security_roles() { return systemFigure("sd_security_roles", "DELEGATION HAS SEPARATE PARTICIPANTS", "tree", ["resource owner", "client application", "authorization server", "resource API"], "Delegate scope, not a password"); }
export function sd_security_code() { return systemFigure("sd_security_code", "USER APPROVAL AND TOKEN EXCHANGE ARE SEPARATE", "sequence", {"actors": ["Client", "Authorization server", "Resource API"], "steps": [[0, 1, "request delegated scope"], [1, 0, "redirect with code"], [0, 1, "exchange code + proof"], [1, 0, "access token"], [0, 2, "use permitted API"]]}, "A code is not the final API credential"); }
export function sd_security_pkce() { return systemFigure("sd_security_pkce", "THE CODE IS BOUND TO AN ATTEMPT'S PROOF", "rows", [["client creates", "verifier V"], ["authorization", "challenge H(V)", "bind to code"], ["redemption", "code + V", "recompute H(V)"], ["intercepted code", "no V", "cannot redeem correctly"]], "Bind the two stages"); }
export function sd_security_revoke_grant() { return systemFigure("sd_security_revoke_grant", "END THE GRANT AND ITS RENEWAL PATH", "flow", ["user revokes client", "invalidate grant", "reject refresh", "bound existing access"], "Revocation has more than one credential"); }
export function sd_security_rbac() { return systemFigure("sd_security_rbac", "ROLES GRANT NAMED ACTIONS IN A SCOPE", "matrix", {"rows": ["viewer", "scorer", "moderator", "owner"], "cols": ["read score", "edit score", "moderate"], "values": [["yes", "no", "no"], ["yes", "yes", "no"], ["yes", "no", "yes"], ["yes", "yes", "yes"]]}, "A role needs a scope"); }
export function sd_security_acl() { return systemFigure("sd_security_acl", "A GRANT NAMES RESOURCE, PRINCIPAL, AND ACTION", "rows", [["object", "clip 7"], ["grant", "Mira \u2192 analyst", "read"], ["request", "analyst reads clip 7", "allowed"], ["other object", "clip 8", "no grant"]], "Sharing is object-specific"); }
export function sd_security_attributes() { return systemFigure("sd_security_attributes", "ALL REQUIRED CONDITIONS MUST HOLD", "flow", ["same tenant", "scorer role", "assigned match", "editing open"], "Define the permission predicate"); }
export function sd_security_effect() { return systemFigure("sd_security_effect", "POLICY CAN CHANGE WHILE WORK WAITS", "sequence", {"actors": ["Requester", "Worker", "Policy store"], "steps": [[0, 1, "request authorized initially"], [2, 2, "permission revoked"], [1, 2, "recheck at effect"], [2, 1, "deny current action"]]}, "Permission is evaluated for an effect"); }
export function sd_security_tls() { return systemFigure("sd_security_tls", "AUTHENTICATE THE ENDPOINT BEFORE TRUSTING PROTECTION", "flow", ["connect to expected host", "validate server identity", "derive session protection", "send credential"], "Encrypted to whom"); }
export function sd_security_at_rest() { return systemFigure("sd_security_at_rest", "STORED CIPHERTEXT AND DECRYPTION AUTHORITY", "split", [["Storage copy", "ciphertext\nno plaintext without key"], ["Authorized app", "key or decrypt permission\ncan access permitted data"]], "Key authority matters"); }
export function sd_security_envelope() { return systemFigure("sd_security_envelope", "PROTECT DATA AND PROTECT ITS KEY SEPARATELY", "tree", ["managed wrapping key", "wrapped data key", "encrypted clip", "access policy + audit"], "A key hierarchy has owners"); }
export function sd_security_secret() { return systemFigure("sd_security_secret", "A CAPABILITY HAS A COMPLETE LIFECYCLE", "flow", ["issue scoped secret", "retrieve by identity", "use without logging", "rotate + revoke"], "A hidden file is not a lifecycle"); }
export function sd_security_password() { return systemFigure("sd_security_password", "VERIFY THROUGH A REVIEWED EXPENSIVE DERIVATION", "flow", ["submitted password", "stored salt + parameters", "password-hash function", "constant-time compare"], "Slow offline guessing deliberately"); }
export function sd_security_hash_capacity() { return systemFigure("sd_security_hash_capacity", "EXPENSIVE WORK NEEDS A BOUNDED FRONT DOOR", "rows", [["assumed verification", "100 ms", "64 MiB"], ["one worker", "10 verifications/s"], ["four workers", "40 verifications/s", "256 MiB"]], "Protect costly anonymous work"); }
export function sd_security_signed() { return systemFigure("sd_security_signed", "AUTHORIZE ISSUANCE, THEN VERIFY THE CAPABILITY", "sequence", {"actors": ["Client", "App", "Object store"], "steps": [[0, 1, "request clip 7"], [1, 1, "check resource policy"], [1, 0, "signed read URL"], [0, 2, "present signed URL"], [2, 0, "verify then serve"]]}, "A copied URL can carry authority"); }
export function sd_security_upload() { return systemFigure("sd_security_upload", "A LIMITED TRANSFER IS NOT AUTOMATIC PUBLICATION", "flow", ["authorize target key", "limited upload grant", "verify stored object", "publish metadata"], "Storage success is one boundary"); }
export function sd_security_cors() { return systemFigure("sd_security_cors", "BROWSER RESPONSE ACCESS HAS ITS OWN PROTOCOL", "sequence", {"actors": ["Other origin page", "Browser", "Heron API"], "steps": [[1, 2, "preflight when required"], [2, 1, "declared origin policy"], [1, 2, "eligible actual request"], [2, 1, "response + policy"], [1, 0, "expose only if allowed"]]}, "CORS is not authentication"); }
export function sd_security_csrf() { return systemFigure("sd_security_csrf", "THE ATTACKER USES THE VICTIM'S BROWSER", "sequence", {"actors": ["Attacker page", "Victim browser", "Heron"], "steps": [[0, 1, "trigger unwanted action"], [1, 2, "request + automatic cookie"], [2, 2, "validate CSRF proof"], [2, 1, "reject missing proof"]]}, "Automatic credentials change the threat"); }
export function sd_security_xss() { return systemFigure("sd_security_xss", "KEEP A TITLE AS DATA THROUGH RENDERING", "flow", ["untrusted title", "context-safe escaping", "text in document", "no execution"], "Data should stay data"); }
export function sd_security_abuse() { return systemFigure("sd_security_abuse", "A PER-USER LIMIT IS NOT A GLOBAL CAPACITY LIMIT", "rows", [["per user", "100 requests/min"], ["50,000 users", "5,000,000 requests/min"], ["aggregate", "83,333.333333/s"], ["needed controls", "global cost budget", "action-specific rules"]], "Count expensive operations"); }
export function sd_security_full_read() { return systemFigure("sd_security_full_read", "EACH BOUNDARY CHECKS ITS OWN AUTHORITY", "flow", ["TLS + session", "tenant + clip policy", "signed read capability", "verify and serve"], "Do not log the credentials"); }
export function sd_security_full_write() { return systemFigure("sd_security_full_write", "PERMISSION AND REPEAT SAFETY BOTH PROTECT THE COMMAND", "flow", ["credential + operation ID", "current action policy", "version + input checks", "commit one effect"], "Authorize the effect that commits"); }
export function sd_security_leaked() { return systemFigure("sd_security_leaked", "REMOVE USABLE AUTHORITY, THEN VERIFY CONTAINMENT", "flow", ["identify exposed key", "revoke + rotate", "update authorized users", "review scoped actions"], "Exposure is a lifecycle event"); }
export function sd_security_contract() { return systemFigure("sd_security_contract", "EVERY CAPABILITY NEEDS PURPOSE AND REVOCATION", "matrix", {"rows": ["session", "access JWT", "API key", "signed URL"], "cols": ["authority boundary", "end validity"], "values": [["current session", "record revoke"], ["issuer + audience", "expiry or state"], ["scoped caller", "key revoke"], ["method + object", "expiry or policy"]]}, "A credential format is not the whole policy"); }
