import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_observability(stage=99) { return systemMap("sd_observability", ["Monitoring goals and telemetry", "Structured logs and request IDs", "Counters, gauges, histograms", "Distributed tracing", "Sampling and collection", "Dashboards and golden signals", "SLIs, SLOs, SLAs, error budgets", "Alerting and incident diagnosis", "Case study: observing one request"], stage); }
export function cover_sd_observability() { return systemCover("sd_observability", 19, ["Monitoring and", "observability"], "Observability and monitoring", ["Monitoring goals and telemetry", "Structured logs and request IDs", "Counters, gauges, histograms", "Distributed tracing", "Sampling and collection", "Dashboards and golden signals", "SLIs, SLOs, SLAs, error budgets", "Alerting and incident diagnosis", "Case study: observing one request"]); }
export function sd_observability_01() { return systemFigure("sd_observability_01", "A HEALTHY PROCESS AND AN UNHAPPY VIEWER", "rows", [["process", "running", "healthy"], ["response", "HTTP success", "old version"], ["user", "freshness fails", "needs update"]], ""); }
export function sd_observability_02() { return systemFigure("sd_observability_02", "BLACK-BOX AND WHITE-BOX EVIDENCE", "sequence", {"actors": ["Probe", "Public route", "API"], "steps": [[0, 1, "normal request"], [1, 2, "authenticate and read"], [2, 0, "validate body, not only status"]]}, ""); }
export function sd_observability_03() { return systemFigure("sd_observability_03", "SYMPTOMS, CAUSES, AND HYPOTHESES", "flow", ["Key change", "Cache misses", "Pool fills", "Read delay"], ""); }
export function sd_observability_04() { return systemFigure("sd_observability_04", "THE TELEMETRY CONTRACT", "rows", [["attempt", "admitted", "completed"], ["command", "key known", "effect committed"], ["outcome", "fresh result", "viewer confirmed"]], ""); }
export function sd_observability_05() { return systemFigure("sd_observability_05", "STRUCTURED LOGGING", "rows", [["event", "score_read_finished", "stable name"], ["fields", "request, result", "version, duration"], ["query", "result = stale", "same event type"]], ""); }
export function sd_observability_06() { return systemFigure("sd_observability_06", "REQUEST IDS AND CORRELATION", "sequence", {"actors": ["Gateway", "API", "DB client"], "steps": [[0, 1, "correlation carried"], [1, 2, "child attempt logged"], [2, 1, "result joins same request"]]}, ""); }
export function sd_observability_07() { return systemFigure("sd_observability_07", "LOGGING ASYNCHRONOUS WORK", "rows", [["API", "command accepted", "event stored"], ["worker", "delivery received", "effect applied"], ["retry", "same event ID", "new attempt"]], ""); }
export function sd_observability_08() { return systemFigure("sd_observability_08", "REDACTION, ACCESS, AND RETENTION", "flow", ["Allowed fields", "Redact at source", "Bounded storage", "Scoped query"], ""); }
export function sd_observability_09() { return systemFigure("sd_observability_09", "COUNTERS AND RATES", "rows", [["begin", "counter sampled", "instance identity"], ["interval", "60,000 attempts", "600 failures"], ["rate", "1,000 per second", "1% failed"]], ""); }
export function sd_observability_10() { return systemFigure("sd_observability_10", "GAUGES AND STATE", "rows", [["capacity", "40 slots", "32 busy"], ["occupancy", "32 / 40", "0.8"], ["waiters", "separate gauge", "delay measured"]], ""); }
export function sd_observability_11() { return systemFigure("sd_observability_11", "HISTOGRAMS AND LATENCY", "rows", [["bound ms", "5", "40", "100", "200"], ["cumulative", "50", "95", "99", "100"], ["interval count", "50", "45", "4", "1"]], ""); }
export function sd_observability_12() { return systemFigure("sd_observability_12", "CARDINALITY AND LABEL BUDGETS", "bars", [["base labels", 360, "series"], ["histogram", 5040, "series"], ["with users", 18000000, "base series"]], ""); }
export function sd_observability_13() { return systemFigure("sd_observability_13", "SPANS AND THE TRACE TREE", "rows", [["request", "200 ms total", "includes child"], ["database", "120 ms child", "inside parent"], ["outside child", "80 ms", "not proven CPU"]], ""); }
export function sd_observability_14() { return systemFigure("sd_observability_14", "CONTEXT PROPAGATION", "sequence", {"actors": ["Ingress", "API", "Dependency"], "steps": [[0, 1, "extract trace context"], [1, 2, "inject parent context"], [2, 1, "child span connected"]]}, ""); }
export function sd_observability_15() { return systemFigure("sd_observability_15", "PARALLEL WORK AND THE CRITICAL PATH", "rows", [["start", "score 120 ms", "profile 80 ms"], ["join", "wait max = 120", "both complete"], ["assembly", "20 ms", "total 140 ms"]], ""); }
export function sd_observability_16() { return systemFigure("sd_observability_16", "ASYNC LINKS, RETRIES, AND SPAN STATUS", "rows", [["input contexts", "request A", "request B"], ["batch span", "link A", "link B"], ["attempt result", "timeout observed", "effect may exist"]], ""); }
export function sd_observability_17() { return systemFigure("sd_observability_17", "HEAD SAMPLING", "flow", ["1,000 requests/s", "Head decision", "Expected 10 traces/s", "24,000 bytes/s"], ""); }
export function sd_observability_18() { return systemFigure("sd_observability_18", "TAIL SAMPLING", "rows", [["incoming", "1,000 traces/s", "wait 10 s"], ["candidates", "10,000 traces", "24,000,000 bytes"], ["decision", "keep slow/error", "handle late spans"]], ""); }
export function sd_observability_19() { return systemFigure("sd_observability_19", "COLLECTOR QUEUES AND EXPORTER FAILURE", "rows", [["overload", "1,200 in/s", "1,000 out/s"], ["after 60 s", "12,000 queued", "bounded capacity"], ["recovery", "400 spare/s", "30 s to drain"]], ""); }
export function sd_observability_20() { return systemFigure("sd_observability_20", "MEASURING THE OBSERVERS", "sequence", {"actors": ["Synthetic source", "Collector", "Query backend"], "steps": [[0, 1, "known test event"], [1, 2, "export and index"], [2, 0, "confirm visible and fresh"]]}, ""); }
export function sd_observability_21() { return systemFigure("sd_observability_21", "TRAFFIC AND USEFUL COMPLETION", "rows", [["offered", "1,000 attempts/s", "includes retry"], ["admitted", "accepted attempts", "after limiter"], ["completed", "useful outcomes", "separate failures"]], ""); }
export function sd_observability_22() { return systemFigure("sd_observability_22", "ERROR RATES AND WEIGHTED AGGREGATION", "rows", [["region A", "9 / 900", "1%"], ["region B", "10 / 100", "10%"], ["fleet", "19 / 1,000", "1.9%"]], ""); }
export function sd_observability_23() { return systemFigure("sd_observability_23", "CPU, MEMORY, AND SATURATION", "flow", ["Demand", "Resource limit", "Wait or reject", "User delay"], ""); }
export function sd_observability_24() { return systemFigure("sd_observability_24", "QUEUE AGE, DEPTH, CONNECTIONS, AND CACHE HITS", "rows", [["queue", "depth and oldest age", "not interchangeable"], ["database", "busy and acquisition wait", "resource boundary"], ["cache", "900 hits / 1,000", "0.9 hit fraction"]], ""); }
export function sd_observability_25() { return systemFigure("sd_observability_25", "SERVICE-LEVEL INDICATORS", "flow", ["Eligible request", "Fresh and timely?", "Good or bad", "Window ratio"], ""); }
export function sd_observability_26() { return systemFigure("sd_observability_26", "OBJECTIVES AND THE ERROR BUDGET", "rows", [["window", "2,592,000,000", "eligible requests"], ["bad fraction", "1 - 0.999", "0.001"], ["budget", "2,592,000", "bad requests"]], ""); }
export function sd_observability_27() { return systemFigure("sd_observability_27", "AGREEMENTS AND MULTIPLE OBJECTIVES", "matrix", {"rows": ["Availability", "Freshness", "Durability"], "cols": ["Fast reply", "Correct version", "Recoverable write"], "values": [["yes", "not enough", "not enough"], ["not enough", "yes", "not enough"], ["not enough", "not enough", "yes"]]}, ""); }
export function sd_observability_28() { return systemFigure("sd_observability_28", "LOW TRAFFIC, WINDOWS, AND MISSING DATA", "rows", [["no traffic", "no eligible events", "ratio undefined"], ["sparse traffic", "few observations", "show count"], ["missing data", "unknown sample state", "freshness warning"]], ""); }
export function sd_observability_29() { return systemFigure("sd_observability_29", "BURN RATE ARITHMETIC", "rows", [["allowed bad", "0.001", "SLO allowance"], ["observed bad", "0.01", "measured interval"], ["burn", "0.01 / 0.001", "10 times"]], ""); }
export function sd_observability_30() { return systemFigure("sd_observability_30", "MULTIWINDOW ALERTS", "flow", ["Long-window burn", "Short-window burn", "Both active", "Page or ticket"], ""); }
export function sd_observability_31() { return systemFigure("sd_observability_31", "ACTIONABLE ALERTS AND RUNBOOKS", "flow", ["User harm", "Named owner", "Bounded action", "Recovery check"], ""); }
export function sd_observability_32() { return systemFigure("sd_observability_32", "INCIDENT HYPOTHESES AND TIMELINE", "sequence", {"actors": ["Responder", "System", "Evidence"], "steps": [[0, 2, "record predicted result"], [0, 1, "apply bounded mitigation"], [1, 2, "measure user outcome"], [2, 0, "confirm or reject hypothesis"]]}, ""); }
export function sd_observability_33() { return systemFigure("sd_observability_33", "THE COMPLETE SCORE-READ TRACE", "sequence", {"actors": ["Viewer", "API", "Cache / DB"], "steps": [[0, 1, "read score with context"], [1, 2, "cache stale, read durable"], [2, 1, "new version returned"], [1, 0, "client validates freshness"]]}, ""); }
export function sd_observability_34() { return systemFigure("sd_observability_34", "THE COMPLETE INGEST-TO-QUERY PATH", "flow", ["SDK buffer", "Collector queue", "Durable backend", "Queryable record"], ""); }
export function sd_observability_35() { return systemFigure("sd_observability_35", "DESIGNING THE OBSERVABILITY FAILURE TEST", "rows", [["disconnected", "user service continues", "queue bounded"], ["queue full", "documented drop", "loss counter"], ["restored", "backlog drains", "event times retained"]], ""); }
export function sd_observability_36() { return systemFigure("sd_observability_36", "FROM INCIDENT REVIEW TO A CHANGED MECHANISM", "flow", ["Observed failure chain", "Specific change", "Repeat failure test", "Check changed outcome"], ""); }
