import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_scaling_patterns(stage=99) { return systemMap("sd_scaling_patterns", ["Replication vs partitioning", "Sharding and consistent hashing", "CQRS and materialized views", "Event sourcing", "Transactional outbox and CDC", "Saga pattern", "Leader election, distributed locks", "Fan-out on write vs on read", "Case study: combining patterns"], stage); }
export function cover_sd_scaling_patterns() { return systemCover("sd_scaling_patterns", 20, ["Scaling", "patterns"], "Scaling patterns", ["Replication vs partitioning", "Sharding and consistent hashing", "CQRS and materialized views", "Event sourcing", "Transactional outbox and CDC", "Saga pattern", "Leader election, distributed locks", "Fan-out on write vs on read", "Case study: combining patterns"]); }
export function sd_scaling_patterns_01() { return systemFigure("sd_scaling_patterns_01", "A LIMIT IS NOT A PATTERN NAME", "rows", [["observed", "read delay", "unknown cause"], ["measurement", "query work", "pool wait"], ["choice", "reduce named work", "test result"]], ""); }
export function sd_scaling_patterns_02() { return systemFigure("sd_scaling_patterns_02", "INVARIANTS BEFORE DISTRIBUTION", "rows", [["read", "expected 7", "state 7"], ["other writer", "commits 8", "state changes"], ["stale writer", "expects 7", "reject"]], ""); }
export function sd_scaling_patterns_03() { return systemFigure("sd_scaling_patterns_03", "REPLICATION CHANGES COPIES", "rows", [["leader", "version 8", "committed"], ["follower", "version 7", "not applied"], ["after apply", "version 8", "read eligible"]], ""); }
export function sd_scaling_patterns_04() { return systemFigure("sd_scaling_patterns_04", "PARTITIONING CHANGES OWNERSHIP", "rows", [["whole demand", "1,000 reads/s", "one owner set"], ["four shards", "250 reads/s mean", "if balanced"], ["key choice", "match locality", "viewer spread"]], ""); }
export function sd_scaling_patterns_05() { return systemFigure("sd_scaling_patterns_05", "PARTITION KEYS AND LOCALITY", "rows", [["primary key", "match", "score + version"], ["derived index", "user", "followed matches"], ["query without key", "scatter", "merge"]], ""); }
export function sd_scaling_patterns_06() { return systemFigure("sd_scaling_patterns_06", "CONSISTENT HASHING AND MOVEMENT", "rows", [["modulo change", "80 / 100 moved", "4 to 5 owners"], ["ideal ring", "1 / 5 space", "new owner"], ["handoff", "copy + routing epoch", "still required"]], ""); }
export function sd_scaling_patterns_07() { return systemFigure("sd_scaling_patterns_07", "HOT KEYS SURVIVE BALANCED HASHING", "rows", [["hot owner", "600 reads/s", "one match"], ["other demand", "400 reads/s", "remaining owners"], ["mitigation", "cache / safe read copies", "preserve write rule"]], ""); }
export function sd_scaling_patterns_08() { return systemFigure("sd_scaling_patterns_08", "RESHARDING WITHOUT TWO OWNERS", "rows", [["copy", "snapshot", "source still owns"], ["catch up", "changes after snapshot", "destination follows"], ["switch", "new epoch", "old owner fenced"]], ""); }
export function sd_scaling_patterns_09() { return systemFigure("sd_scaling_patterns_09", "CQRS SEPARATES MODELS", "rows", [["command model", "validate transition", "enforce version"], ["query model", "score card", "reader shape"], ["deployment", "can share DB", "not forced services"]], ""); }
export function sd_scaling_patterns_10() { return systemFigure("sd_scaling_patterns_10", "MATERIALIZED VIEWS PAY EARLY", "rows", [["source", "version 8", "authoritative"], ["projection", "card version 7", "temporarily old"], ["apply", "card version 8", "readable"]], ""); }
export function sd_scaling_patterns_11() { return systemFigure("sd_scaling_patterns_11", "PROJECTION UPDATES AND DUPLICATE DELIVERY", "rows", [["first delivery", "apply event", "store identity"], ["ack lost", "broker retries", "same identity"], ["second delivery", "identity exists", "no second effect"]], ""); }
export function sd_scaling_patterns_12() { return systemFigure("sd_scaling_patterns_12", "LAG, CATCH-UP, AND READ-YOUR-WRITES", "rows", [["pause 10 s", "20 events/s", "200 backlog"], ["recovery", "100 out - 20 in", "80 spare/s"], ["catch-up", "200 / 80", "2.5 s"]], ""); }
export function sd_scaling_patterns_13() { return systemFigure("sd_scaling_patterns_13", "EVENT SOURCING PRESERVES DOMAIN CHANGES", "rows", [["history", "ordered domain events", "authority"], ["replay", "apply transition rule", "derived state"], ["current view", "latest score", "rebuildable"]], ""); }
export function sd_scaling_patterns_14() { return systemFigure("sd_scaling_patterns_14", "EXPECTED VERSIONS AND CONCURRENT APPENDS", "rows", [["both commands", "expect 7", "same prior state"], ["first append", "7 to 8", "commit"], ["second append", "expected 7, actual 8", "conflict"]], ""); }
export function sd_scaling_patterns_15() { return systemFigure("sd_scaling_patterns_15", "SNAPSHOTS AND REPLAY COST", "rows", [["full replay", "1,000,000 / 20,000", "50 s"], ["snapshot tail", "1,000 / 20,000", "0.05 s"], ["validity", "source + schema + checksum", "verify first"]], ""); }
export function sd_scaling_patterns_16() { return systemFigure("sd_scaling_patterns_16", "REPLAY, SCHEMA EVOLUTION, AND OUTSIDE EFFECTS", "rows", [["live event", "derive state", "effect workflow"], ["replay event", "derive state", "no new charge"], ["old schema", "version interpreter", "same meaning"]], ""); }
export function sd_scaling_patterns_17() { return systemFigure("sd_scaling_patterns_17", "THE DUAL-WRITE FAILURE WINDOW", "rows", [["DB first", "state commits", "crash before send"], ["broker first", "event visible", "DB may fail"], ["needed", "one durable boundary", "recover publication"]], ""); }
export function sd_scaling_patterns_18() { return systemFigure("sd_scaling_patterns_18", "TRANSACTIONAL OUTBOX", "rows", [["transaction", "score update", "outbox insert"], ["commit", "both durable", "or neither"], ["relay", "send event", "duplicate possible"]], ""); }
export function sd_scaling_patterns_19() { return systemFigure("sd_scaling_patterns_19", "RELAYS, CLAIMS, AND ACKNOWLEDGEMENT LOSS", "rows", [["claim", "row assigned", "recoverable lease"], ["broker accepts", "event durable there", "ack may be lost"], ["restart", "row still pending", "resend same ID"]], ""); }
export function sd_scaling_patterns_20() { return systemFigure("sd_scaling_patterns_20", "CDC CHECKPOINTS AND RETAINED LOGS", "rows", [["snapshot", "consistent boundary", "log position"], ["stream", "later commits", "checkpoint"], ["reader stalls", "log retained", "storage pressure"]], ""); }
export function sd_scaling_patterns_21() { return systemFigure("sd_scaling_patterns_21", "SAGA STEPS AND LOCAL COMMITS", "rows", [["reserve", "local commit", "pending workflow"], ["charge", "local commit", "confirmed effect"], ["grant", "local commit", "or recover"]], ""); }
export function sd_scaling_patterns_22() { return systemFigure("sd_scaling_patterns_22", "COMPENSATION IS A NEW ACTION", "rows", [["charge", "2,500 cents", "confirmed"], ["grant fails", "workflow recovery", "refund requested"], ["compensation", "refund confirmed", "history remains"]], ""); }
export function sd_scaling_patterns_23() { return systemFigure("sd_scaling_patterns_23", "ORCHESTRATION STATE MACHINES", "rows", [["persisted state", "charge pending", "stable command ID"], ["restart", "reissue / query", "same effect identity"], ["late reply", "check current state", "accept or reconcile"]], ""); }
export function sd_scaling_patterns_24() { return systemFigure("sd_scaling_patterns_24", "CHOREOGRAPHY AND EVENT CONTRACTS", "rows", [["payment", "charged event", "durable intention"], ["access", "react and grant", "repeatable effect"], ["failure", "named recovery owner", "workflow visible"]], ""); }
export function sd_scaling_patterns_25() { return systemFigure("sd_scaling_patterns_25", "LEADER ELECTION AND AUTHORITY", "rows", [["coordinator", "owner agreed", "generation stored"], ["old owner", "cannot renew", "may still run"], ["new owner", "current generation", "resource enforces"]], ""); }
export function sd_scaling_patterns_26() { return systemFigure("sd_scaling_patterns_26", "LEASES AND PAUSE EXPIRY", "rows", [["lease", "10 s authority", "work lasts 15 s"], ["expiry", "new worker allowed", "old one paused"], ["resume", "5 s beyond lease", "must be rejected"]], ""); }
export function sd_scaling_patterns_27() { return systemFigure("sd_scaling_patterns_27", "FENCING TOKENS AT THE RESOURCE", "rows", [["old worker", "older generation", "paused"], ["new worker", "newer generation", "accepted"], ["old resumes", "older generation", "resource rejects"]], ""); }
export function sd_scaling_patterns_28() { return systemFigure("sd_scaling_patterns_28", "DISTRIBUTED LOCKS AND THE SMALLEST SCOPE", "rows", [["row invariant", "conditional update", "local atomicity"], ["external coordination", "lease + owner", "more states"], ["release", "check owner identity", "do not delete successor"]], ""); }
export function sd_scaling_patterns_29() { return systemFigure("sd_scaling_patterns_29", "FAN-OUT ON WRITE", "rows", [["publish", "100 posts/s", "10,000 recipients"], ["write work", "1,000,000 entries/s", "async workers"], ["read", "recipient feed", "precomputed references"]], ""); }
export function sd_scaling_patterns_30() { return systemFigure("sd_scaling_patterns_30", "FAN-OUT ON READ", "rows", [["read demand", "50 reads/s", "200 candidates"], ["query work", "10,000 candidates/s", "gather + merge"], ["page", "stable ordering boundary", "cursor"]], ""); }
export function sd_scaling_patterns_31() { return systemFigure("sd_scaling_patterns_31", "HYBRID FAN-OUT AND SKEW", "rows", [["ordinary posts", "write fan-out", "recipient entries"], ["large publisher", "read-time candidates", "no massive push"], ["merge", "dedup + permissions", "stable ordering"]], ""); }
export function sd_scaling_patterns_32() { return systemFigure("sd_scaling_patterns_32", "RANKING, DELETION, AND STABLE PAGES", "rows", [["first page", "order + tie breaker", "cursor boundary"], ["new arrivals", "before boundary", "session policy"], ["next page", "same context", "filter deleted"]], ""); }
export function sd_scaling_patterns_33() { return systemFigure("sd_scaling_patterns_33", "THE COMPLETE SCORER COMMIT", "rows", [["input", "key + expected version", "validate"], ["transaction", "score + outbox + result", "one commit"], ["response", "durable version", "repeatable result"]], ""); }
export function sd_scaling_patterns_34() { return systemFigure("sd_scaling_patterns_34", "THE COMPLETE DERIVED PUBLICATION", "rows", [["relay", "stable event ID", "match order"], ["projection", "version applied", "checkpoint"], ["other effects", "separate progress", "separate recovery"]], ""); }
export function sd_scaling_patterns_35() { return systemFigure("sd_scaling_patterns_35", "THE CRASH MATRIX", "rows", [["before commit", "no effect", "retry command"], ["after commit", "outbox pending", "relay resumes"], ["after send", "possible duplicate", "consumer dedups"], ["after effect", "possible redelivery", "durable progress"]], ""); }
export function sd_scaling_patterns_36() { return systemFigure("sd_scaling_patterns_36", "CHOOSING FEWER PATTERNS AT CHANGED SCALE", "rows", [["changed demand", "read traffic grows", "write rule same"], ["possible change", "read copies / index", "measure benefit"], ["retained authority", "same invariant", "less new machinery"]], ""); }
