import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_interview_method(stage=99) { return systemMap("sd_interview_method", ["Requirements gathering", "Back-of-the-envelope estimation", "API design", "Data model", "High-level architecture", "Critical request flows", "Bottlenecks and scaling", "Failures and consistency", "Trade-offs and the final answer"], stage); }
export function cover_sd_interview_method() { return systemCover("sd_interview_method", 21, ["The design", "interview"], "The system design interview", ["Requirements gathering", "Back-of-the-envelope estimation", "API design", "Data model", "High-level architecture", "Critical request flows", "Bottlenecks and scaling", "Failures and consistency", "Trade-offs and the final answer"]); }
export function sd_interview_method_01() { return systemFigure("sd_interview_method_01", "FUNCTIONAL REQUIREMENTS AS ACTIONS", "rows", [["actor", "scorer / viewer", "who acts"], ["action", "update / read / upload", "what happens"], ["result", "committed / fresh / pending", "observable boundary"]], ""); }
export function sd_interview_method_02() { return systemFigure("sd_interview_method_02", "NON-FUNCTIONAL REQUIREMENTS AS TESTS", "rows", [["latency", "operation + population", "measurement boundary"], ["durability", "accepted state", "named failure"], ["consistency", "specific invariant", "not whole-system word"]], ""); }
export function sd_interview_method_03() { return systemFigure("sd_interview_method_03", "SCOPE, PRIORITIES, AND CONFLICT", "rows", [["partition", "sites cannot agree", "same seat requested"], ["serve both", "availability locally", "winner may conflict"], ["preserve winner", "delay / reject", "contract choice"]], ""); }
export function sd_interview_method_04() { return systemFigure("sd_interview_method_04", "ASSUMPTIONS AND UNRESOLVED QUESTIONS", "rows", [["given", "user actions", "binding contract"], ["assumed", "rate / bytes / failure", "labelled illustrative"], ["computed", "derived demand", "units retained"]], ""); }
export function sd_interview_method_05() { return systemFigure("sd_interview_method_05", "DAILY REQUESTS, AVERAGE, AND PEAK", "rows", [["daily", "8,640,000 requests", "86,400 seconds"], ["average", "100 requests/s", "divide"], ["peak", "1,000 requests/s", "multiply by 10"]], ""); }
export function sd_interview_method_06() { return systemFigure("sd_interview_method_06", "CONCURRENCY FROM COMPATIBLE RATES", "rows", [["throughput", "1,000 per second", "same population"], ["mean time", "0.2 seconds", "same boundary"], ["mean in flight", "200 requests", "stable system"]], ""); }
export function sd_interview_method_07() { return systemFigure("sd_interview_method_07", "STORAGE, RETENTION, AND COPIES", "rows", [["daily", "4,320,000,000 bytes", "assumed all-write exercise"], ["30 days", "129,600,000,000", "logical"], ["three copies", "388,800,000,000", "before overhead"]], ""); }
export function sd_interview_method_08() { return systemFigure("sd_interview_method_08", "BANDWIDTH AND FAN-OUT", "rows", [["API", "2,000,000 bytes/s", "responses"], ["live deliveries", "1,000,000 per second", "events times viewers"], ["live payload", "200,000,000 bytes/s", "not API rate"]], ""); }
export function sd_interview_method_09() { return systemFigure("sd_interview_method_09", "RESOURCE MODELING AND OUTCOMES", "rows", [["create", "clip + upload session", "pending"], ["complete bytes", "verified object", "processing"], ["publish", "playable state", "client can query"]], ""); }
export function sd_interview_method_10() { return systemFigure("sd_interview_method_10", "VALIDATION, AUTHENTICATION, AND AUTHORIZATION", "rows", [["input", "form and size", "validation"], ["identity", "caller established", "authentication"], ["effect", "permission + invariant", "authorization"]], ""); }
export function sd_interview_method_11() { return systemFigure("sd_interview_method_11", "PAGINATION AND CHANGING LISTS", "rows", [["first page", "order + tie breaker", "last boundary"], ["new clips", "list shifts", "offset changes"], ["continuation", "cursor context", "permissions checked"]], ""); }
export function sd_interview_method_12() { return systemFigure("sd_interview_method_12", "IDEMPOTENCY AND UNKNOWN OUTCOMES", "rows", [["first attempt", "key + payload", "effect commits"], ["reply lost", "outcome unknown", "client retries"], ["repeat", "same key and intent", "return stored result"]], ""); }
export function sd_interview_method_13() { return systemFigure("sd_interview_method_13", "ENTITIES, KEYS, AND RELATIONSHIPS", "rows", [["clip", "key + owner", "authoritative"], ["object", "object identity", "bytes outside DB"], ["feed/search", "clip reference", "derived"]], ""); }
export function sd_interview_method_14() { return systemFigure("sd_interview_method_14", "ATOMIC STATE TRANSITIONS", "rows", [["precondition", "authorized + object complete", "prior state"], ["local commit", "state + work intention", "atomic"], ["repeat", "already completed", "safe result"]], ""); }
export function sd_interview_method_15() { return systemFigure("sd_interview_method_15", "INDEXES FROM ACCESS PATTERNS", "rows", [["playback", "clip ID", "point lookup"], ["profile", "owner + order", "range lookup"], ["cost", "extra writes + bytes", "per index"]], ""); }
export function sd_interview_method_16() { return systemFigure("sd_interview_method_16", "AUTHORITATIVE AND DERIVED DATA", "rows", [["metadata", "existence + permission", "authority"], ["search", "discovery representation", "can lag"], ["serve bytes", "check current contract", "derived cannot grant"]], ""); }
export function sd_interview_method_17() { return systemFigure("sd_interview_method_17", "A BOX NEEDS A JOB", "rows", [["component", "one necessary job", "owned state"], ["arrow", "payload + timing", "acknowledgement"], ["separation", "required reason", "not default"]], ""); }
export function sd_interview_method_18() { return systemFigure("sd_interview_method_18", "CONTROL PATHS AND BYTE PATHS", "rows", [["control", "permission + session", "API"], ["bytes", "5,000,000,000 bytes", "object path"], ["completion", "validate object", "metadata transition"]], ""); }
export function sd_interview_method_19() { return systemFigure("sd_interview_method_19", "SYNCHRONOUS AND ASYNCHRONOUS BOUNDARIES", "rows", [["before response", "validate + commit", "required"], ["commit record", "downstream intention", "durable"], ["after response", "notify / project", "recoverable workers"]], ""); }
export function sd_interview_method_20() { return systemFigure("sd_interview_method_20", "OWNERSHIP AND SERVICE BOUNDARIES", "rows", [["one invariant", "one authority", "local rule"], ["separate ownership", "network workflow", "new failures"], ["modular process", "clear code boundaries", "shared transaction"]], ""); }
export function sd_interview_method_21() { return systemFigure("sd_interview_method_21", "THE COMPLETE READ FLOW", "rows", [["read", "permission + freshness", "validate"], ["cache", "version acceptable?", "hit or fetch"], ["response", "version + outcome", "viewer boundary"]], ""); }
export function sd_interview_method_22() { return systemFigure("sd_interview_method_22", "THE COMPLETE WRITE FLOW", "rows", [["command", "key + expected 7", "validate"], ["commit", "version 8 + intention", "durable"], ["retry", "same key", "stored result"]], ""); }
export function sd_interview_method_23() { return systemFigure("sd_interview_method_23", "THE COMPLETE UPLOAD FLOW", "rows", [["session", "pending clip", "authorized upload"], ["parts", "50 \u00d7 100,000,000", "retry individual part"], ["complete", "verify object", "processing intention"]], ""); }
export function sd_interview_method_24() { return systemFigure("sd_interview_method_24", "THE COMPLETE LIVE-UPDATE FLOW", "rows", [["event", "committed version", "stream"], ["gateway", "bounded connections", "bounded output queue"], ["reconnect", "last version", "replay or snapshot"]], ""); }
export function sd_interview_method_25() { return systemFigure("sd_interview_method_25", "FIND THE LIMITING RESOURCE", "rows", [["symptom", "read delay", "user boundary"], ["resource evidence", "pool / disk / CPU", "name limit"], ["change", "relevant mechanism", "same test workload"]], ""); }
export function sd_interview_method_26() { return systemFigure("sd_interview_method_26", "NORMAL CAPACITY AND FAILURE HEADROOM", "rows", [["normal", "5 \u00d7 300", "1,500 requests/s"], ["one lost", "4 \u00d7 300", "1,200 requests/s"], ["headroom", "1,200 - 1,000", "200 requests/s"]], ""); }
export function sd_interview_method_27() { return systemFigure("sd_interview_method_27", "THE CACHE OUTAGE CALCULATION", "rows", [["normal", "1,000 \u00d7 0.1", "100 source reads/s"], ["cache absent", "all reads fall through", "1,000 source reads/s"], ["amplification", "1,000 / 100", "10 times"]], ""); }
export function sd_interview_method_28() { return systemFigure("sd_interview_method_28", "QUEUE RECOVERY AND BACKPRESSURE", "rows", [["burst", "1,200 in - 1,000 out", "200 growth/s"], ["after 60 s", "12,000 tasks", "waiting"], ["recovery", "1,000 - 600 spare", "30 s"]], ""); }
export function sd_interview_method_29() { return systemFigure("sd_interview_method_29", "CRASH WINDOWS AND UNKNOWN PROGRESS", "rows", [["before commit", "no durable effect", "retry"], ["after commit", "effect exists", "reply may be absent"], ["after send", "delivery may repeat", "dedup effect"]], ""); }
export function sd_interview_method_30() { return systemFigure("sd_interview_method_30", "REPLICA LAG AND READ-YOUR-WRITES", "rows", [["write reply", "version 8", "acknowledged"], ["follower", "version 7", "not yet adequate"], ["read policy", "authority / wait / pending", "bounded"]], ""); }
export function sd_interview_method_31() { return systemFigure("sd_interview_method_31", "RECOVERY TIME AND RECOVERABLE HISTORY", "rows", [["starting point", "backup / replica", "failure-specific"], ["recovery", "restore + replay", "validate"], ["cutover", "dependencies + reconciliation", "user check"]], ""); }
export function sd_interview_method_32() { return systemFigure("sd_interview_method_32", "GRACEFUL DEGRADATION AND ADMISSION", "rows", [["optional dependency", "unavailable", "omit safely"], ["core operation", "separate capacity", "continues"], ["overload", "early bounded rejection", "controlled retry"]], ""); }
export function sd_interview_method_33() { return systemFigure("sd_interview_method_33", "COMPARE ALTERNATIVES ON THE SAME CONTRACT", "rows", [["same contract", "invariant + failure", "same workload"], ["choice A", "benefit", "cost"], ["choice B", "benefit", "cost"]], ""); }
export function sd_interview_method_34() { return systemFigure("sd_interview_method_34", "THE COMPLETE WHITEBOARD ANSWER", "rows", [["contract", "actions + guarantees", "assumptions"], ["flow", "authority + commit", "recovery"], ["defense", "bottleneck + trade-off", "test"]], ""); }
export function sd_interview_method_35() { return systemFigure("sd_interview_method_35", "CHANGING ONE REQUIREMENT", "rows", [["old contract", "URL valid until expiry", "bounded revocation"], ["new contract", "immediate denial", "serving-time authority"], ["cost", "extra state / wait", "new failure policy"]], ""); }
export function sd_interview_method_36() { return systemFigure("sd_interview_method_36", "PRACTICE BY REPRODUCING MECHANISMS", "rows", [["reproduce", "flow from memory", "name each state"], ["interrupt", "failure at boundary", "recover safely"], ["transfer", "new system", "same mechanism"]], ""); }
