import { systemFigure, systemMap, systemCover } from '../lib/system-figures.js';

export function where_sd_practice_designs(stage=99) { return systemMap("sd_practice_designs", ["URL shortener, Pastebin, notifications", "Chat, WhatsApp, feed, Dropbox", "Drive, autocomplete, tickets, payments", "Uber, YouTube, Instagram, Docs", "Metrics, scheduler, Kafka, cache", "Designing Redis, Kafka and a database", "Deep dive: money and conflicts", "Deep dive: capacity", "Putting it all together"], stage); }
export function cover_sd_practice_designs() { return systemCover("sd_practice_designs", 22, ["Practice", "designs"], "Practice system designs", ["URL shortener, Pastebin, notifications", "Chat, WhatsApp, feed, Dropbox", "Drive, autocomplete, tickets, payments", "Uber, YouTube, Instagram, Docs", "Metrics, scheduler, Kafka, cache", "Designing Redis, Kafka and a database", "Deep dive: money and conflicts", "Deep dive: capacity", "Putting it all together"]); }
export function sd_practice_designs_01() { return systemFigure("sd_practice_designs_01", "URL SHORTENER: CREATION AND REDIRECT", "rows", [["create", "candidate key", "unique insert"], ["collision", "existing owner", "retry candidate"], ["redirect", "mapping + state", "destination"]], ""); }
export function sd_practice_designs_02() { return systemFigure("sd_practice_designs_02", "PASTEBIN: BYTES AND EXPIRY", "rows", [["upload", "pending bytes", "not visible"], ["publish", "metadata committed", "readable"], ["expiry", "deny now", "cleanup later"]], ""); }
export function sd_practice_designs_03() { return systemFigure("sd_practice_designs_03", "RATE LIMITER: ATOMIC TOKEN DECISION", "rows", [["before", "20 tokens", "last refill"], ["refill", "add 20, cap 100", "40 available"], ["spend", "25 tokens", "15 remain"]], ""); }
export function sd_practice_designs_04() { return systemFigure("sd_practice_designs_04", "NOTIFICATIONS: INTENT, ATTEMPT, AND RECEIPT", "rows", [["commit", "notification intention", "durable"], ["attempt", "provider accepts", "receipt boundary"], ["restart", "outcome unknown", "query or safe repeat"]], ""); }
export function sd_practice_designs_05() { return systemFigure("sd_practice_designs_05", "CHAT: DURABLE ORDER AND RECONNECT", "rows", [["send", "client message ID", "authorize"], ["append", "conversation order", "durable"], ["reconnect", "last position", "fetch gap"]], ""); }
export function sd_practice_designs_06() { return systemFigure("sd_practice_designs_06", "WHATSAPP-STYLE MESSAGING: DEVICE FAN-OUT", "rows", [["message", "durable identity", "recipient relation"], ["fan-out", "device A", "device B offline"], ["receipt", "per device progress", "retry safely"]], ""); }
export function sd_practice_designs_07() { return systemFigure("sd_practice_designs_07", "NEWS FEED: WORK PLACEMENT AND RANKING", "rows", [["write fan-out", "1,000,000 entries/s", "early cost"], ["read fan-out", "10,000 candidates/s", "request cost"], ["serve", "rank + permission", "derived references"]], ""); }
export function sd_practice_designs_08() { return systemFigure("sd_practice_designs_08", "DROPBOX-STYLE SYNC: BLOCKS AND VERSIONS", "rows", [["base", "50 blocks", "version 7"], ["changed", "2 blocks uploaded", "200,000,000 bytes"], ["publish", "expected version", "new manifest"]], ""); }
export function sd_practice_designs_09() { return systemFigure("sd_practice_designs_09", "GOOGLE DRIVE-STYLE FILES: SHARING AND UPLOAD STATE", "rows", [["bytes", "resumable upload", "pending object"], ["metadata", "owner + parents + ACL", "authority"], ["publish", "revision verified", "download permission"]], ""); }
export function sd_practice_designs_10() { return systemFigure("sd_practice_designs_10", "SEARCH AUTOCOMPLETE: PREFIX CANDIDATES", "rows", [["keystroke", "normalized prefix", "input version"], ["lookup", "bounded candidates", "rank"], ["response", "latest input only", "ignore old reply"]], ""); }
export function sd_practice_designs_11() { return systemFigure("sd_practice_designs_11", "TICKET BOOKING: ONE SEAT, ONE WINNER", "rows", [["contenders", "same seat", "atomic claim"], ["winner", "hold identity", "expiry"], ["late payment", "hold no longer current", "reconcile"]], ""); }
export function sd_practice_designs_12() { return systemFigure("sd_practice_designs_12", "PAYMENTS: INTENT, LEDGER, AND RECONCILIATION", "rows", [["intent", "2,500 cents", "stable identity"], ["timeout", "provider outcome unknown", "reconcile"], ["ledger", "debit = credit", "net zero"]], ""); }
export function sd_practice_designs_13() { return systemFigure("sd_practice_designs_13", "UBER-STYLE MATCHING: CANDIDATES AND ASSIGNMENT", "rows", [["location", "sequence + freshness", "spatial bucket"], ["matching", "nearby candidates", "not authority"], ["assignment", "conditional state", "one commitment"]], ""); }
export function sd_practice_designs_14() { return systemFigure("sd_practice_designs_14", "YOUTUBE-STYLE VIDEO: PROCESSING AND PLAYBACK", "rows", [["original", "verified stored object", "processing job"], ["renditions", "versioned outputs", "not yet published"], ["playback", "complete manifest", "CDN segments"]], ""); }
export function sd_practice_designs_15() { return systemFigure("sd_practice_designs_15", "INSTAGRAM-STYLE MEDIA: FEED REFERENCES AND ACCESS", "rows", [["original", "2,000,000,000 bytes/day", "before derivatives"], ["publish", "verified media version", "feed event"], ["serve", "current permission", "cached reference not enough"]], ""); }
export function sd_practice_designs_16() { return systemFigure("sd_practice_designs_16", "GOOGLE DOCS-STYLE COLLABORATION: CONCURRENT OPERATIONS", "rows", [["base", "same document version", "concurrent inserts"], ["authority", "order / transform", "canonical operation"], ["clients", "reconcile pending", "same document"]], ""); }
export function sd_practice_designs_17() { return systemFigure("sd_practice_designs_17", "METRICS AND LOGGING PLATFORM: BOUNDED INGESTION", "rows", [["metrics", "5,760,000 samples/day", "bounded series"], ["logs", "43,200,000,000 bytes/day", "payload only"], ["query", "indexed + fresh", "not ingest ack"]], ""); }
export function sd_practice_designs_18() { return systemFigure("sd_practice_designs_18", "DISTRIBUTED JOB SCHEDULER: CLAIM AND FENCING", "rows", [["claim", "task + generation", "lease"], ["pause / expiry", "replacement allowed", "old worker can return"], ["effect", "fence or dedup", "safe completion"]], ""); }
export function sd_practice_designs_19() { return systemFigure("sd_practice_designs_19", "KAFKA-STYLE EVENT LOG: APPEND AND REPLAY", "rows", [["append", "key selects partition", "leader assigns offset"], ["replicate", "acknowledgement rule", "durable boundary"], ["consume", "effect then progress", "replay retained history"]], ""); }
export function sd_practice_designs_20() { return systemFigure("sd_practice_designs_20", "DISTRIBUTED CACHE: PLACEMENT AND SOURCE PROTECTION", "rows", [["memory", "210,000,000 bytes", "assumed item model"], ["copies", "630,000,000 bytes", "three full copies"], ["node loss", "miss surge", "source protection"]], ""); }
export function sd_practice_designs_21() { return systemFigure("sd_practice_designs_21", "DESIGN REDIS ITSELF: PROTOCOL AND EXECUTION", "rows", [["socket bytes", "partial frame", "parser state"], ["complete command", "validate types", "execute"], ["reply", "bounded output", "slow client policy"]], ""); }
export function sd_practice_designs_22() { return systemFigure("sd_practice_designs_22", "DESIGN KAFKA ITSELF: SEGMENTS AND VISIBILITY", "rows", [["append", "active segment", "local log end"], ["replication", "followers catch up", "safe boundary"], ["fetch", "offset + max bytes", "bounded batch"]], ""); }
export function sd_practice_designs_23() { return systemFigure("sd_practice_designs_23", "DESIGN DROPBOX ITSELF: LOCAL SCAN TO REMOTE COMMIT", "rows", [["local change", "watch + rescan", "stable content"], ["remote publish", "verified blocks", "conditional manifest"], ["local apply", "temporary bytes", "atomic replace"]], ""); }
export function sd_practice_designs_24() { return systemFigure("sd_practice_designs_24", "DESIGN A DATABASE ITSELF: PAGES, WAL, AND RECOVERY", "rows", [["update", "memory page + log record", "transaction"], ["commit", "log durability boundary", "acknowledge"], ["restart", "recover log", "rebuild page state"]], ""); }
export function sd_practice_designs_25() { return systemFigure("sd_practice_designs_25", "PAYMENT TIMEOUT: THE FULL RECONCILIATION TRACE", "rows", [["provider", "charge exists", "reply lost"], ["local", "pending / unknown", "no second intent"], ["reconcile", "confirmed reference", "ledger once"]], ""); }
export function sd_practice_designs_26() { return systemFigure("sd_practice_designs_26", "BOOKING EXPIRY: OLD OWNER MEETS NEW WINNER", "rows", [["old hold", "expires", "generation obsolete"], ["new hold", "current owner", "seat allocated"], ["old completion", "identity mismatch", "refund workflow"]], ""); }
export function sd_practice_designs_27() { return systemFigure("sd_practice_designs_27", "MESSAGE RECEIPTS: ACCEPTANCE IS NOT READING", "rows", [["server", "durably accepted", "not device proof"], ["device", "stored acknowledgement", "not read proof"], ["reader", "read observation", "policy dependent"]], ""); }
export function sd_practice_designs_28() { return systemFigure("sd_practice_designs_28", "TWO CONCURRENT INSERTS, ONE CANONICAL ORDER", "rows", [["base", "ab, position 1", "A:X and B:Y"], ["local edits", "A:aXb", "B:aYb"], ["server A then B", "B position 1 to 2", "aXYb"], ["after reconcile", "A:aXYb", "B:aXYb"]], ""); }
export function sd_practice_designs_29() { return systemFigure("sd_practice_designs_29", "LIVE FAN-OUT: GATEWAY AND LINK ARITHMETIC", "rows", [["events", "20 per second", "50,000 recipients"], ["egress", "1,000,000 deliveries/s", "200,000,000 bytes/s"], ["gateways", "five minimum", "failure spare separate"]], ""); }
export function sd_practice_designs_30() { return systemFigure("sd_practice_designs_30", "TRANSFER AND INCREMENTAL-SYNC ARITHMETIC", "rows", [["full file", "5,000,000,000 bytes", "500 s at assumed rate"], ["changed blocks", "200,000,000 bytes", "two blocks"], ["reused", "4,800,000,000 bytes", "48 blocks"]], ""); }
export function sd_practice_designs_31() { return systemFigure("sd_practice_designs_31", "RETENTION BUDGETS FOR LOGS AND METRICS", "rows", [["logs seven days", "302,400,000,000 bytes", "payload only"], ["metrics seven days", "40,320,000 samples", "before encoding"], ["contract", "query / audit / replay", "different retention"]], ""); }
export function sd_practice_designs_32() { return systemFigure("sd_practice_designs_32", "QUEUE OVERLOAD AND RECOVERY CAPACITY", "rows", [["burst", "200 tasks/s excess", "60 s"], ["backlog", "12,000 tasks", "bounded"], ["recovery", "400 spare/s", "30 s"]], ""); }
export function sd_practice_designs_33() { return systemFigure("sd_practice_designs_33", "THE INVARIANT MATRIX ACROSS PRACTICE SYSTEMS", "rows", [["booking", "one seat winner", "seat authority"], ["payment", "one intent effect", "ledger / provider relation"], ["feed", "derived candidates", "current permission"]], ""); }
export function sd_practice_designs_34() { return systemFigure("sd_practice_designs_34", "A FAILURE DRILL SHARED BY EVERY DESIGN", "rows", [["lost reply", "durable effect exists", "stable retry identity"], ["obsolete owner", "successor active", "resource rejects"], ["copy absent", "extra demand", "bounded fallback"]], ""); }
export function sd_practice_designs_35() { return systemFigure("sd_practice_designs_35", "HERON END TO END: ONE COMPLETE DESIGN", "rows", [["score", "atomic command commit", "event intention"], ["live", "ordered event + projection", "gateway recovery"], ["media", "verified bytes + processing", "published manifest"]], ""); }
export function sd_practice_designs_36() { return systemFigure("sd_practice_designs_36", "THE NEXT REHEARSAL AND THE BOUNDARY OF THESE DESIGNS", "rows", [["rehearse", "contract + flow", "from memory"], ["interrupt", "named hard boundary", "safe recovery"], ["change", "one requirement", "predict mechanism"]], ""); }
